### PR TITLE
Moved `abel.tools.vmi.find_image_center_by_slice()` to `abel.tools.center`

### PR DESCRIPTION
**Pull request by stggh**
As per #98, #90, moved `tests/test_tools_vmi.py to test_tools_center.py`, corrected examples and unit tests. Ran `pep8` on `center.py`.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Thanks @stggh! This looks good to me. Any comments from @DhrubajyotiDas, @rth, or @ldes89150 before I merge this?

**Comment by DhrubajyotiDas** [comment]
Looks good to me. I've made a few changes to the codebase since the last PR merge, but nothing conflicts with @stggh's changes here, so no issues on this front.

**Comment by ldes89150** [comment]
Great!! Then I can merge them into my PR #101

**Comment by DanHickstein** [comment]
Cool - merged!

**Pull request merged**
