### PR TITLE
Adding Sphinx documentation for PyAbel

### PR DESCRIPTION
**Pull request by rth**
Following issue #25, this PR adds a draft documentation for PyAbel using Sphinx.

As suggested by @DanHickstein this setup uses the readthedocs.org theme, and [Napoleon](https://sphinxcontrib-napoleon.readthedocs.org/en/latest/index.html) for Numpy style docstrings. 

In addition, this setup uses the [`recommonmark`](https://github.com/rtfd/recommonmark) package to process either .rst or .md documentation files. Markdown for some parts of the documentation would be nice, and we could then potentially reuse the same files between Sphinx and the github wiki.

To build the documentation locally you need to have `Sphinx` and `recommonmark` installed, and the html pages can be generated with:
   
     cd PyAbel/doc/
     make html

The html files currently produced with this command are accessible at http://r0h.eu/it/static/d/PyAbel/index.html although more work is necessary in order to ensure that all docstings are compatible with Numpy style and to add some general explanations. 

In addition, more work would be necessary to automate deployment of the documentation somewhere (for instance to github pages).  I would like to it this latter point before merging this PR.

@DanHickstein Sorry for not responding earlier in issue #25, I completely agree with your comments there. 

**Edit:**  [`sphinx_rtd_theme`](https://github.com/snide/sphinx_rtd_theme/)  also needs to be installed.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Great work @rth!!

What about hosting the docs on readthedocs.org? Not that I have done much research into the options, but this seems like an easy one...

I made an account on readthedocs.org, so now there is a site for PyAbel: http://pyabel.readthedocs.org/en/latest/

I doesn't work quite yet, but I think that it should after things are tweaked.

**Comment by stggh** [comment]
There is a fair bit of work required for `hansenlaw.py` as sphinx et al. does not appear to appreciate ascii art. No matter, this change is good.

My attempt at running `make html` inside of @rth's doc directory (doc branch) gave an error. However, this may be system set-up issue on my Linux system (?).

>[vuvpc5:.+/rth/PyAbel/doc]$ make html
>sphinx-build -b html -d build/doctrees   source build/html
>Running Sphinx v1.2.3
>loading pickled environment... not yet created
>
>Exception occurred:
> File "/usr/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
>    suffixpattern = '*' + suffix
>TypeError: cannot concatenate 'str' and 'list' objects
>The full traceback has been saved in /tmp/sphinx-err-z4ovtb.log, if you want to report the issue to the >developers.
>Please also report this if it was a user error, so that a better error message can be provided next time.
>A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
>Makefile:55: recipe for target 'html' failed
>make: *** [html] Error 1

**Comment by rth** [comment]
@DanHickstein  Hosting is readthedocs.org is a good idea. Since now we have not reached the 1.0 yet, and  there is a lot of things that change in the interface, I think we could just update the docs everything we push to the repo (to keep them in sync). This could be apparently acchieved with [webhooks](https://read-the-docs.readthedocs.org/en/latest/webhooks.html#webhooks). @DanHickstein would you mind activating it in github account if this works for you.

@stggh I think ascii art should still work, but you would probably have to wrap it into some .rst markdown to mark it as code (not sure which though, this need to be looked into). As to the error you are getting, sorry I forgot to tell that  [`sphinx_rtd_theme`](https://github.com/snide/sphinx_rtd_theme/) also need to be installed. This might be what is causing this error. Otherwise this should work in PY2.7 and PY3. Let me know if this was the issue.

**Comment by DanHickstein** [comment]
@rth Yes, the webhook sounds awesome. I activated it in the github account. I think that we can also have documentation for each version release, but I'm slightly confused about how exactly this works: http://docs.readthedocs.org/en/latest/versions.html

@stggh, I think that you can achieve a literal block (fixed width text) by using two colons and then indenting the following text: 

http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#common-rest-concepts

**Comment by stggh** [comment]
@rth 
No joy with `spinx_rtd_theme`. I have `apt-get installed` every PY2.7 `python-sphinx-*` and `sphinx*`. The error log:
>
># Sphinx version: 1.2.3
># Python version: 2.7.10
># Docutils version: 0.12 release
># Jinja2 version: 2.8
># Loaded extensions:
>Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
>    warningiserror, tags, verbosity, parallel)
>  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 145, in __init__
>    self._init_env(freshenv)
>  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 191, in _init_env
>    return self._init_env(freshenv=True)
>  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 173, in _init_env
>    self.env.find_files(self.config)
>  File "/usr/lib/python2.7/dist-packages/sphinx/environment.py", line 350, in find_files
>    self.srcdir, config.source_suffix, exclude_matchers=matchers))
>  File "/usr/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
>    suffixpattern = '*' + suffix
>TypeError: cannot concatenate 'str' and 'list' objects

I am not sure how to initiate the doc build for PY3.
I will test my Mac OSX build at home on the weekend.

@DanHickstein 
Thanks.

**Comment by DanHickstein** [comment]
``make html`` worked on my Mac after following the instructions here:
http://read-the-docs.readthedocs.org/en/latest/getting_started.html

I readthedocs set to automatically synchronize with ``PyAbel/master``. However, you can set up your own readthedocs on your fork in order to test things (make sure that you set the correct branch in Advanced Settings). I did this for my own fork (which I made the same as @rth's latest fork): 
http://pyabel-dh-fork.readthedocs.org/en/latest/

It showed up, but for some reason none of the doc strings get imported. My html builds locally, but not on readthedocs.org...

**Comment by stggh** [comment]
@DanHickstein, @rth,  :: does the job for maintaining the ascii art. The docs build locally and look nice. I have had less joy with readthedocs.org, but I have only skimmed the instructions.

**Comment by DanHickstein** [comment]
I'm also having trouble getting the docs to work on readthedocs.org. Apparently if you use numpy or other C-based packages, then you need to use a workaround: http://read-the-docs.readthedocs.org/en/latest/faq.html 

I tried this, but still can get my docs to build on rtd.org...

**Comment by rth** [comment]
@DanHickstein  Yes, there was some issues with C extensions on readthedocs.org 

The last few commits should fix that with the approaches proposed in their FAQ. Essentially this removes the requirement to have numpy installed when installing PyAbel on readthedocs, than mocks (with `unittest.mock` all the scipy/numpy related modules). 

The docs should work now, and they build in my fork https://pyabel-rth.readthedocs.org/en/latest/abel.html#module-abel.benchmark 
@DanHickstein Also in the PyAbel account on readthedocs.org under Admin>Advanced settings, could you please check the "Install your project inside a virtualenv using setup.py install" option for this to work? Thanks.

**Comment by DanHickstein** [comment]
@rth, I selected the virtualenv option of readthedocs.org. It still gives an error regarding numpy, but I think that this is just because we have not merged this PR yet.

**Comment by rth** [comment]
@DanHickstein Yes, sorry, sure it will not work on the main PyAbel branch as long as this is not merged. We should probably go ahead and merge it. There will be subsequent PRs to fix doc string formatting anyway, so if anything remains to do here, we can add it to those PR.

**Comment by DanHickstein** [comment]
Fine with me to merge this, but @stggh still has PR https://github.com/PyAbel/PyAbel/pull/68 outstanding, and we usually cause all sorts of problems for him when we update the master branch while he's working on something. 

@stggh, are you close to being ready to merge https://github.com/PyAbel/PyAbel/pull/68?

**Comment by rth** [comment]
@DanHickstein You are right, we should merge PR #68 first...

**Comment by stggh** [comment]
@DanHickstein, @rth, @DhrubajyotiDas: I would be very happy for PR #68 to be merged. It contains many changes for the better. I have even taken the trouble to run pep8 ;-)   [not sure that I agree with blank space around `%` though].

**Comment by DanHickstein** [comment]
Should we go ahead and merge this one now as well?

@stggh: blank space around ``%`` is, indeed, madness! :)

**Pull request merged**
