### PR TITLE
Included discussion of background subtraction in comparison.rst

### PR DESCRIPTION
**Pull request by DanHickstein**
Following up on #306, this adds a brief discussion of the importance of background subtraction to comparison.rst.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Here is what that section of the docs looks like now. New paragraph is the last paragraph:
image

**Review by MikhailRyazanov — APPROVED** [review]
Looks good!

**Comment by MikhailRyazanov** [comment]
@DanHickstein, could you please also include a small correction to the next section?
`rbasex` supports the forward transform, so it should be “`rbasex` (F, S)”.

**Comment by DanHickstein** [comment]
Sure! I changed that line. I'll go ahead and merge this tomorrow (Monday) unless you have more suggestions.

**Comment by DanHickstein** [comment]
Whoops, another forgotten PR. Apologies for my slothfulness!

I'm going to go ahead and merge this, since it's a relatively minor change to the docs. @stggh, @MikhailRyazanov: just let me know if you'd like modifications and I'll make a new PR for them.

**Pull request merged**
