### PR TITLE
Hansen and Law algorithm updates

### PR DESCRIPTION
**Pull request by stggh**
The main issue is that ```reproject_into_polar()``` does not appear to handle even pixel sized images, due to the use of (integer,integer) coordinate centre, and associated ```np.meshgrid()```, as discussed in issue #39.  Edit: I take it back ```index_coords()``` accepts origin=(x,y). Just need to pass origin=(x,y) via tools.calculate_speeds()```, I think.

NB ```iabel_hansenlaw()``` performs the correct inverse Abel transform, so the code is still good to merge, with a caveat on the speed distribution, that is nearly correct.

### CODE REVIEW

**Comment by rth** [comment]
This is great!

Just a suggestion that I forgot to mention in the orginal PR about the `freecpus`. I think a more conventional approach would be just to set `ncpus=`, as `freecpus` can be potentially confusing. For instance, say you have a dual core multithreaded laptop, so it has 2 CPU cores, but htop shows 4 CPUs. You won't get much speed improvement above 2 parallel processes, but I have a doubt whether `mp.cpu_count()` returns 4 or 2 (probably 4). The point is you aways have to do the arithmetics of how many cores you have vs how many cores you want to run this on. Also, I think that it's fine to run on all avalable cpu, as the OS should handle the load balancing, so there is no need to set `all_cpus  - 1` as the default, I think, no? 

Also allowing to fall back to a non parallel implementation would be nice (unless `mp.Pool(1).map` is equivalent to the built-in `map`), as the tracebacks from withing `Pool.map` can be a bit confusing. So what do you think about something like this (or replace `ncpus` by some name you find more intuitive)?

     iabel_hansenlaw (... ,   ncpus='all')

          if ncpus == 'all':
               pool = mp.Pool() # I think this uses all cpus (need to check)
               pmap =  pool.map
          elif ncpus > 1:
               pool = mp.Pool(processes=ncpus) 
               pmap  = pool.map
           elif ncpus == 1:
               pmap = map # fall back to a non parallel implementation with the built-in map
           else:
               raise ValueError('Wrong value for the input parameter ncpus={}'.format(ncpus))

           # then use pmap as before

what do you think about it?

Also as a side note, how much speed speed up did you get from using numba JIT on `iabel_hansenlaw_transform`? I agree with @DanHickstein earlier comments, because it has quite a few nested loop and essentially operates on indices, there should be some room for optimization (I was thinking `Cython` for `iabel_hansenlaw_transform`, as I'm already using it in my `direct` implementation, so that won't add dependencies unlike `numba`) But we can discuss this at some later point, after the direct implementation is merged.

Finally, you would have to rebase this on the current PyAbel master, since github shows that it can't be automatically merged right now :)

**Comment by stggh** [comment]
Thanks, Roman.  I will try to implement your suggestions tomorrow. 

numa JIT gave only a fraction of a second "speed up", something like 14.5s cf 14.7s (for a particular test case) and so, is not a worthwhile change. Cython may be a possibility.

BTW, the speed calculation should really include \sin\theta in the sum over angle (if it is summed in angle. I have not yet fully understood ```np.sum(polarIM,axis=1)```).

**Comment by DanHickstein** [comment]
@rth's intuition for parallel processing agrees with what I found testing Hansen–Law a few days ago. On my MacBook i7, ``mp.cpu_count()=4``, since it's dual core with hyperthreading. Setting ``free_cpus=3`` runs in 13 seconds. ``free_cpus=2`` runs in 7 seconds (nearly 2x speedup). Setting ``free_cpus=2``or anything lower (and I tried -99) have the same 7 sec runtime. 

Also, there is no noticeable delay in the responsiveness of the system, so it seems fine to run on all the available cores (though it would appear that hyperthreading means that many processors are lying about their true parallel processing capability).

Okay, maybe we should ignore all of that, because I think that I figured out how to just vectorize the outer loop (the loop over the rows) and now it runs in 0.2 seconds with no parallel processing calls (seems too good to be true...). I just passed the whole quadrant to ``iabel_hansenlaw_transform`` and iterated over each column at once. 

Here's the repo with the code: 
https://github.com/DanHickstein/PyAbel/tree/hacking-hansen-law
Let me know what you think...

--
And yes, you are correct that the calc_speeds should include a factor of sin(theta)*R in order to take into account that the object is going to have more volume as the distance from the central axis becomes larger. I think that what we are currently doing is a correct integration of the central slice, and I would like to keep this capability in the ``calc_speeds`` function, since I actually use this all of time in other aspects of my research. Possibly we could include a keyword argument ``use_jacobian=True`` or ``volume_element=True`` (I think that these are the correct terms, but my Calculus III class was a long time ago at this point). This way users could select if they are looking for a simple angle integration of a 2D image or if they want us to take into account the cylindrical symmetry to give them the distribution of the real 3D object. The difference is important, because information about theta is lost in the returned 1D array, so users cannot simply multiply or divide the array to obtain the different behavior. 

Also, as @rth pointed out a while back, the name ``calc_speeds`` is only meaningful to the photoelectron/photoion community, and we should change the name to something like ``integrate_angular`` to indicate an integration over all angular coordinates.

**Comment by DanHickstein** [comment]
So, I think that I'm just going to merge this in order to preserve the improvements to the quadrants code in tools.py. 

Then I can include my changes in a separate PR.

**Comment by stggh** [comment]
Wow! @DanHickstein an amazing code improvement. Well done! This is what open source is all about. 

The speed distribution is still an issue. On close inspection of the O2- speed spectrum, HL appears to have less resolution, which implies that the image centre is offset. The origin offset (-0.5,-0.5) applied to even images makes the HL speed align with basex speed, but basex is speed is (slightly) incorrect for even images. i.e. the (-1/2,-1/2) pixel offset made the HL speed align with an incorrect basex speed. More investigation required.

**Comment by DanHickstein** [comment]
Yes, the calc_speeds is still not doing something quite right. We'll need to think about this more. 

Take a look at the vectorized code (and other changes) in https://github.com/PyAbel/PyAbel/pull/47 and let me know if you're okay to go ahead with the merge.

**Pull request merged**
