### PR TITLE
Some code and documentation improvements

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
I was playing with type hints and static code analysis ([mypy](https://mypy.readthedocs.io/en/stable/), to be specific) and found some minor errors and inconsistencies in our code (and docstrings), so here are their corrections...

### CODE REVIEW

**Comment by stggh** [comment]
@MikhailRyazanov - Neat!  I did not know about `mypy`. What is the `mypy.ini` file that you are using, if you do not mind sharing.

**Comment by MikhailRyazanov** [comment]
I've actually tried to make typing stub files for the whole PyAbel: https://github.com/MikhailRyazanov/PyAbel-stubs. I guess, it would be useful to incorporate them into PyAbel once they become usable enough... The ``mypy.ini`` for testing the stubs themselves is included there, but using them might be better with somewhat different options.

**Comment by MikhailRyazanov** [comment]
It is strange that Travis tests for Python 3 now fail with something typing-related, although I haven't done anything typing-related in this code. Searching _the internets_ doesn't help much except that it might be related to a conflict between the apparently preinstalled `dataclasses` package (`.../site-packages/dataclasses.py`) with the built-in dataclasses (`/usr/lib/python3.x/dataclasses.py`). Let me try to uninstall it...

**Comment by MikhailRyazanov** [comment]
OK, uninstalling "dataclasses" on Travis helped indeed. Hopefully, soon they will correct this themselves (everything was working fine until recently)...

**Review by stggh — APPROVED** [review]
Looks good. Thanks for the heads-up about `mypy`.

**Comment by DanHickstein** [comment]
I know nothing about mypy, but these changes look great! Thanks Mikhail!

**Review by DanHickstein — APPROVED** [review]

**Comment by MikhailRyazanov** [comment]
Thanks!

(I've actually noticed some additional strange things but forgot to mention them here because they need some further analysis and discussion. I'll open an issue later...)

**Pull request merged**
