### PR TITLE
working on getting the paper into comparison.rst

### PR DESCRIPTION
**Pull request by DanHickstein**
I already started working on this on my own fork, so I'm making a PR so that you can track my progress. I've started moving the information from the manuscript into comparison.rst.

Now, I'm thinking that we should combine comparison.rst and transform_methods.rst. Since comparison.rst will now have a list of all of the methods, transform_methods.rst is basically redundant. And we don't want to maintain another list of description of the transform methods.

I'll try to finish this up in the next few days.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Here is what it looks like so far: https://pyabel--291.org.readthedocs.build/en/291/transform_methods/comparison.html

**Comment by DanHickstein** [comment]
Okay, I finally got all of the material from our manuscript into comparison.rst. It's fairly rough right now. I'll try to get some additional editing done.

**Comment by DanHickstein** [comment]
Interestingly, rBasex has a shift with respect to the other methods: 

image

**Comment by DanHickstein** [comment]
Okay, I just proofread the comparison.rst and fixed a bunch of things. It's probably ready for someone else to look at it now. https://pyabel--291.org.readthedocs.build/en/291/transform_methods/comparison.html

I made this PR against the "comparison" branch. So, if someone else wants to take over, you can just merge this into "comparison" and keep working on it.

**Comment by stggh** [comment]
Good work @DanHickstein. I will take a deeper look later.

> Interestingly, rBasex has a shift with respect to the other methods:

API has been changed since our paper. The call requires the `origin`:
```python
   if label == 'rbasex':
        trans = transFunc(IModd, direction="inverse", origin='ll')[0]
```
Screen Shot 2020-05-01 at 11 07 40

**Comment by DanHickstein** [comment]
Okay, I think that I fixed it now. Thanks for your help @stggh!!

**Comment by MikhailRyazanov** [comment]
@DanHickstein, thanks for incorporating this!

You have several PDF files included in `fig_...`, but they don't seem to be used, neither generated by current scripts (I guess, they are remnants of some experiments). If this was unintentional, please remove them before we merge this.

**Comment by DanHickstein** [comment]
Yeah, the PDF files were unintentional. Guess I need to include .pdf in the gitignore as well :)

**Comment by MikhailRyazanov** [comment]
OK, @DanHickstein, since this PR got conflicts with the target branch (due to directory renaming here while adding new files there) and has unwanted PDF files in the history, I have rebased it on the current PyAbel:comparison, filtered the PDF files out, and then merged manually. It looks like everything was incorporated correctly, so I'm closing this at GitHub.

**Pull request closed without merging**
