### PR TITLE
PDF documentation and updates

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
An attempt to enable downloadable PDF documentation on Read the Docs (even if this doesn't work, at least building it locally would become possible). See #340 for some history.

On my system it now builds without errors and produces usable results, although there is a general problem with pagination: since most images are inserted into the text flow, they cannot be floated without creating a mess, thus when a relatively tall image doesn't fit to the rest of the page, a page break is forced, creating a big gap. And since stupid Sphinx doesn't allow overriding LaTeX float options for individual figures (without resorting to black magic), even those large figures with captions, which should have been floated, are contribution to the problem.

There is also one noticed issue that multiple references to the same footnote *sometimes* don't work. It's a mystery why, because some of them do work, and I don't know what to do about this. However, this seems to be a minor nuisance.

I've also made many minor improvements in formatting and linking (particularly, between method invocations and descriptions, to further address #289) and updated some URLs (with the help from ``make linkcheck``!).

A shameful overlook that correcting the ``SampleImage`` scaling in PR #339 broke the rBasex regularization examples is also addressed here.

P.S. Unfortunately, almost every file is affected, so maybe considering each commit successively instead of looking at the overall change would be easier, or maybe not... Please review carefully!

### CODE REVIEW

**Comment by MikhailRyazanov** [comment]
Hey, where are all the “checks”?!

**Review by stggh — APPROVED** [review]
@MikhailRyazanov your attention to detail is mind blowing. Excellent work as usual.

`livehtml`, `latexpdf` work on my Ubuntu 21.10 system, once `latexmk` was installed. 

`linkcheck` fails with 
```
(transform_methods/two_point: line   43) broken    https://github.com/PyAbel/PyAbel/pull/155#issuecomment-200630188 - Anchor 'issuecomment-200630188' not found
```

**Comment by MikhailRyazanov** [comment]
> `livehtml`, `latexpdf` work on my Ubuntu 21.10 system, once `latexmk` was installed.

OK, great! RTD in fact provides no control over the build commands, so they either must have `latexmk` available (if they use default Sphinx tools) or implement some equivalent (maybe just run `pdflatex` [3 times, as usual](https://tex.stackexchange.com/questions/53235/why-does-latex-bibtex-need-three-passes-to-clear-up-all-warnings)...).

> `linkcheck` fails with

Because GitHub [has broken](https://github.com/github/feedback/discussions/7370#discussioncomment-2374779) links to comments in long discussions... I don't think that we can do anything until/unless they repair this somehow.

**Review by DanHickstein — APPROVED** [review]
The PDF builds great on my system, and it looks FANTASTIC! Incredible work as always Mikhail!

**Comment by MikhailRyazanov** [comment]
Great! Then I'm going to merge this and see whether RTD can make a downloadable PDF...

**Comment by MikhailRyazanov** [comment]
OK, success!

According to [the log](https://readthedocs.org/api/v2/build/16418873.txt), LaTeX ran without any outstanding issues, and I can now see the PDF under “Downloads” at https://pyabel.readthedocs.io/en/latest/. The file looks a little bit different from my local build (due to different fonts and slightly different styles), but also without any obvious issues. HTMLs also look good.

**Comment by DanHickstein** [comment]
Awesome!

Seeing all of the documentation in a single PDF is really impressive. It makes me proud of what we have build here! Good work everyone!

**Pull request merged**
