### PR TITLE
Tweaked example_linbasex to allow building on readthedocs.org

### PR DESCRIPTION
**Pull request by DanHickstein**
To address https://github.com/PyAbel/PyAbel/issues/193,
I downsampled the example image from 1024x1024 to 512x512 to avoid using too much RAM, which seems to have exceeded the 1 GB limit on readthedocs.org.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Before (killed):
https://readthedocs.org/projects/pyabel-dh-fork/builds/5002767/

After (success!):
https://readthedocs.org/projects/pyabel-dh-fork/builds/5002791/

**Comment by stggh** [comment]
Subtle. Good work.

**Comment by stggh** [comment]
I think the merge occurred before my comment was sent.

`example_linbasex.py` line 75, the `axis` limits need changing to `ax2.axis(xmin=50, xmax=250, ymin=-1.5, ymax=1.8)`

I can fix in my PR if needed.

**Comment by DanHickstein** [comment]
Whoops, pressed the merge button a minute too early. Yeah, if you could take care of that in your PR, that would be awesome.

**Pull request merged**
