### PR TITLE
Enabling OSX testing on travis

### PR DESCRIPTION
**Pull request by DanHickstein**
Following https://github.com/PyAbel/PyAbel/issues/323, we should enable testing on MacOS is possible. TravisCI seems to support this. 

I think that we just need to edit the `.travis.yml` file. This is my first attempt. Will probably take a few iterations.

### CODE REVIEW

**Comment by DanHickstein** [comment]
I tried enabling Windows testing on Travis as well, but it's labeled as experimental, and it took longer than 10 minutes for the build to _start_, so I gave up. I think that we should have at least one build run as quickly as possible so that people can spot major errors quickly. So, we can just continue to use AppVeyor for our Windows build needs.

**Comment by MikhailRyazanov** [comment]
Great, nice to see that macOS testing works (and passes)!
As I understand, this is using the default preinstalled Python 2.7. Will it make sense to try testing with the latest Python 3 also?

**Comment by DanHickstein** [comment]
I was trying to test on python 3.9 on MacOS. Let me see if I can get that to happen.

**Comment by DanHickstein** [comment]
Huh, I can't figure out how to set the python version on MacOS on Travis.

**Comment by MikhailRyazanov** [comment]
Well, [here](https://docs.travis-ci.com/user/languages/python/) they show a red warning that “Python builds are not available on the macOS and Windows environments.” :–) So maybe it's not supposed to work at all. On the other hand, it [could](https://stackoverflow.com/questions/56608429) be possible to install [using Homebrew](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos), although I'm not sure this is really worth investigating (but if yes, perhaps all other builds should better be temporary disabled to avoid overusing them)...

**Comment by MikhailRyazanov** [comment]
@DanHickstein, maybe we should merge this as is (but squashed) for now? Testing with the built-in Python is still useful and better than nothing, especially before continuing with #327...

**Comment by MikhailRyazanov** [comment]
Well, I'm going to merge this to see how it works...

**Comment by DanHickstein** [comment]
Awesome! Thanks for moving this forward.

**Pull request merged**
