### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by DanHickstein**
updated readme to mention Hansen&Law transform. (Previously it said BASEX was the only option, which is no longer correct.)

### CODE REVIEW

**Comment by stggh** [comment]
Good, apart from minor typo 'recusrive'

**Comment by DanHickstein** [comment]
Ah, thanks :)

**Comment by stggh** [comment]
Also, forgot to mention, in ```hansenlaw.py``` Parameters: Img should be changed to IM (or vice versa)

**Comment by DanHickstein** [comment]
Good catch!

**Comment by stggh** [comment]
Comment is still slightly mangled:
``` IM: a nRows/2 x n/2 numpy vector = one row of one quadrant of the image orientated top/left```  
---->   ```IM: a n2 x n2 numpy array = one quadrant of the image oriented top/left```

**Comment by DanHickstein** [comment]
Whoops, already merged. If you have a minute, go ahead and make the changes and submit a new PR.

**Comment by stggh** [comment]
Ok, will do.

**Pull request merged**
