### PR TITLE
Optimization flags for Cython

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
Our Conda packages are currently broken at least for some users (#320), most probably because the build server creates the precompiled Cython module (for the `direct_C` method) with a more advanced instruction set than users' CPUs have. So let's try to remove the `-march=native` optimization flag to avoid this.

It also makes sense to replace `-O2` with [`-Ofast`](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Ofast) to make the code faster by [sacrificing strict IEEE compliance](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ffast-math) (which we don't need).

And let's try to do similar optimizations for Windows by adding corresponding MSVC flags.

### CODE REVIEW

**Comment by MikhailRyazanov** [comment]
This passes all unit tests on Travis and AppVeyor, including `test_direct.py::test_direct_c_python_correspondence`, which probably means that the Cython module is built correctly. Or not? The logs mention `cython` but are very terse about building/installing `pyabel`. Is it possible to see more information about this?

**Comment by DanHickstein** [comment]
I think that if it passes that test that you mention then that confirms that the Direct-C implementation is working okay. 

I think that you can see as much as I can see on Travis. But, I'm happy to give you full access to the Travis and Appveyor accounts if we can figure out how to do that. I log into travis through my GitHub account, so I wonder if you do the same if you will have access to the PyAbel organization account on Travis...

**Review by DanHickstein — APPROVED** [review]

**Comment by stggh** [comment]
This builds with `-O2` and `-Ofast`, with the last optimization overriding the others :
```
gcc -pthread -B /home/stg121/anaconda3/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/stg121/anaconda3/include -I/home/stg121/anaconda3/include -fPIC -O2 -isystem /home/stg121/anaconda3/include -fPIC -I/home/stg121/anaconda3/lib/python3.9/site-packages/numpy/core/include -I/home/stg121/anaconda3/lib/python3.9/site-packages/numpy/core/include -I/home/stg121/anaconda3/include/python3.9 -c abel/lib/direct.c -o build/temp.linux-x86_64-3.9/abel/lib/direct.o -Ofast
```
Timing corresponds to `-Ofast`:
```
=== Forward Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
direct_C                2.5        17.8       118.8       873.6


=== Inverse Abel transform ====================================

Method              n = 257     n = 513    n = 1025    n = 2047
---------------------------------------------------------------
direct_C                2.9        19.5       131.1       909.1
```

Q: Is there a way to check a "direct" conda install?

**Review by stggh — APPROVED** [review]
Looks good to me.

**Comment by MikhailRyazanov** [comment]
@stggh, could you please rerun full timing benchmarks for `direct_C` on your i7-9700 and i7-6700 to update the documentation? Redoing the slow `direct_Python` is probably unnecessary, since it shouldn't be affected.

**Comment by MikhailRyazanov** [comment]
@DanHickstein, I've just checked and now see that Travis indeed lets me sign in using my GitHub account. However, it was giving access to full raw logs even without that. So I'm basically wondering how to increase the verbosity level to something like what @stggh [showed](https://gist.github.com/stggh/75151d92c4adc8548dba8af1c14814eb) for local manual installation.

**Comment by stggh** [comment]
> rerun full timing benchmarks for direct_C on your i7-9700 and i7-6700

Sorry for the delay, there were some power outages in Canberra due to summer storms.

i7-9700 direct_C.dat
```
# direct_C        iabel(ms)           
     5             0.16358
    9             0.17085
   17             0.18188
   33             0.20043
   65             0.27702
  129             0.68181
  257             2.87535
  513            16.77957
 1025           115.07356
 2049           845.21606
 4097          8275.82846
 8193         64248.76927
16385        496151.16668
```

i7-6700:
```
# direct_C        iabel(ms)           
    5             0.12384
    9             0.12569
   17             0.13269
   33             0.14659
   65             0.21511
  129             1.34027
  257             6.28215
  513            40.42908
 1025           195.81982
 2049          1271.44220
 4097         11299.37075
 8193         87618.95179
16385        689934.61746
```

n=32769  to follow.

**Comment by MikhailRyazanov** [comment]
Thanks! This is not urgent. :–)

The new data, however, look somewhat strange compared to what we had (excerpts for i7-9700):
```
new:
  513            16.77957
 1025           115.07356
 2049           845.21606

old:
  513            17.88147
 1025           141.61429
 2049           998.25061
```
So it's in fact not _much_ faster, and the old numbers differ significantly from what you've [shown](https://github.com/PyAbel/PyAbel/issues/320#issuecomment-996633638) for `-O2 -march=native` previously. Has anything changed since these old benchmarks?..

**Comment by stggh** [comment]
> anything changed since these old benchmarks

Quite a lot, with the Ubuntu upgrades.  I will rerun the original `-O2 -march=native` to compare.

**Comment by MikhailRyazanov** [comment]
> Quite a lot, with the Ubuntu upgrades.

I guess, in this particular case only the GCC behavior matters (unless Cython started to produce something very odd), and it's hard to believe that GCC has unlearned how to do “native” optimization properly. :–) Maybe these old benchmarks were done with “cpu-boost” that you've mentioned?

**Comment by stggh** [comment]
> done with “cpu-boost”

Here are 3 cases: `-O2 -march=native`, `-Ofast`, and `-Ofast` with turbo-boost, which allows the cpu to clock above 3GHz, upto 4.7GHz, but the CPUs are thermally throttledif they overheat. Ubuntu does not appear to vary the system fan much.

```python
(base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-O2native/direct_C.dat 
# direct_C        iabel(ms)           
    5             0.16429
    9             0.16482
   17             0.17304
   33             0.19958
   65             0.28705
  129             0.77420
  257             3.81089
  513            26.30118
 1025           199.85150
 2049          1534.62534
 4097         13651.89078
 8193        107196.82974
16385        844188.81459
```
```python
(base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-Ofast/direct_C.dat 
# direct_C        iabel(ms)           
    5             0.18062
    9             0.18418
   17             0.18896
   33             0.21321
   65             0.28323
  129             0.66076
  257             2.73759
  513            16.79285
 1025           115.55955
 2049           848.43757
 4097          8166.23876
 8193         64050.76444
16385        494223.99664
```
```python
base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-turboboost/direct_C.dat 
# direct_C        iabel(ms)           
    5             0.10344
    9             0.10513
   17             0.11019
   33             0.12276
   65             0.22574
  129             0.54793
  257             2.18825
  513            12.41999
 1025            84.80508
 2049           590.95230
 4097          6382.18254
 8193         47139.45847
16385        357451.63618
```

For comparison here are the `daun` timings:

```python
(base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-O2native/daun.dat
# daun            iabel(ms)           basis(ms)
    5             0.02588             0.03166
    9             0.02642             0.04905
   17             0.02741             0.08336
   33             0.02983             0.15140
   65             0.04019             0.29196
  129             0.05551             0.56958
  257             0.11707             1.18491
  513             0.40301             2.56132
 1025             2.42408             5.54391
 2049            21.27464            13.15279
 4097           106.00833            36.23711
 8193           650.13345           102.84730
16385          4408.67954           328.57914
32769         32200.80419          1197.42810
```
```python
(base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-Ofast/daun.dat
# daun            iabel(ms)           basis(ms)
    5             0.02824             0.03500
    9             0.02880             0.05338
   17             0.02991             0.08945
   33             0.03261             0.16150
   65             0.04367             0.30396
  129             0.05917             0.60204
  257             0.12150             1.24379
  513             0.39853             2.65196
 1025             2.53089             5.78947
 2049            21.15319            13.50023
 4097           105.59027            37.75018
 8193           666.67169           105.53140
16385          4507.41972           347.19364
32769         33546.68668          1194.75573
```
```python
(base) [Gibbo:.+tg121/Test-Abel]$ cat working-9700-turboboost/daun.dat
# daun            iabel(ms)           basis(ms)
    5             0.01751             0.02246
    9             0.01775             0.03382
   17             0.01869             0.05724
   33             0.02029             0.10572
   65             0.03594             0.19887
  129             0.04816             0.39677
  257             0.10172             0.82936
  513             0.35214             1.75034
 1025             2.31038             3.86967
 2049            19.43850             8.97384
 4097            98.20195            24.90506
 8193           632.09796            69.35378
16385          4408.82186           220.59236
32769         31741.15315           779.51158
```

The `daun` `-O2 march=native` results are similar to `PyAbel-MR-direct_C-setup/doc/transform_methods/comparison/fig_benchmarks/i7-9700_Linux/daun.dat`:
```python
# daun            iabel(ms)           basis(ms)
    5             0.01711             0.02373
    9             0.01955             0.03707
   17             0.02057             0.06232
   33             0.02293             0.11695
   65             0.02886             0.22029
  129             0.04329             0.43562
  257             0.10706             0.90285
  513             0.42341             1.89876
 1025             4.23736             4.05734
 2049            19.78891             9.56412
 4097           109.93354            27.52181
 8193           727.86471            74.85047
16385          4903.41616           227.30092
32769         37612.45776           818.95221
```

**Comment by MikhailRyazanov** [comment]
Thanks, @stggh!

Daun should not depend on Cython flags, so this makes sense. And I guess that turbo boost has little effect on it probably because matrix operations even at “normal” speed already load the CPU to the limit (I've read somewhere that CPUs can even reduce its clock rate when doing such heavy calculations to avoid overheating, so if this indeed happens, then “allowing” higher clock doesn't really change the actual clock).

I've updated the benchmarks using your [first data](https://github.com/PyAbel/PyAbel/pull/331#issuecomment-997296178) as the most complete. It's still faster than before, and probably not very important anyway...

**Comment by MikhailRyazanov** [comment]
> The logs mention cython but are very terse about building/installing pyabel. Is it possible to see more information about this?

OK, I've added the `-v` option to `pip install` on both Travis and AppVeyor, so now they report the details, and it can be seen that Cython indeed works properly in all cases.

Unless somebody knows how to test this on Conda before merging, I think, we can just release a new version in the near future and see what happens. It shouldn't get worse at least. :–)

@DanHickstein, I've noticed that AppVeyor has tests for Python 3.7 and 3.8, but they both in fact reached their [end of support](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions), and 3.10 is [already available](https://www.appveyor.com/docs/lang/python/). Maybe we should switch these 3.7 and 3.8 to 3.9 and 3.10? Travis doesn't have 3.10 yet, so its current configuration with 3.8 and 3.9 looks fine.

**Comment by DanHickstein** [comment]
It's fine with me to bump the Travis versions. It should just be a simple matter of changing the version numbers in .travis.yml (but probably some bug will pop up! :) )

**Comment by MikhailRyazanov** [comment]
OK. It seems that Python 3.10 is available by itself but is not compatible with their current Miniconda. So I've just updated the versions to 3.8 and 3.9.

**Comment by DanHickstein** [comment]
Yeah, this has been my experience with new versions of Python on the CI platforms. You can only use one version behind the state-of-the-art. 3.10 will only work once 3.11 is released :)

**Pull request merged**
