### PR TITLE
Preparations for v0.9.0rc1 release (v0.9.0 pre-release)

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
OK, let's try to release a new version. As described in #361, it will be v0.9.0, but this is a pre-release to test that the updated release process works as expected.

Draft of the release notes:
```
This is a release candidate for v0.9.0. 

Corrections and improvements to the lin-BASEX method implementation, as well as
improvements and extensions of the analytical Abel-transform tools.

Here is a full list of changes in v0.8.5:
* Correct behavior of relative basis_dir in basex under Python 2 (PR #336).
* Improvements in tools.analytical.SampleImage class: more consistent and
  intuitive interface, accurate Abel transform for existing images, additional
  sample images with exact Abel transform (PR #339, #352).
* Analytical Abel transform of axially symmetric piecewise polynomials in
  spherical coordinates (PR #339).
* Offline HTML and PDF documentation is now available at Read the Docs and can
  be built locally (PR #343, #348, #349).
* **Important** changes in the **lin-BASEX** implementation (PR #357):

  - It was erroneously producing even-sized images with offset origin. Now the
    output is odd-sized and properly centered.
  - Output images for radial_step > 1 were scaled down by the same factor. Now
    they have the save size as the input.
  - The sign of Beta for odd Legendre orders is reversed to be consistent with
    PyAbel conventions (zero angle is upwards, towards smaller row indices).

* Transform() with method='linbasex' now always stores the radial, Beta and
  projection attributes, so there is no need to pass return_Beta=True
  in transform_options (PR #357).
```

### CODE REVIEW

**Comment by DanHickstein** [comment]
Looks good to me!

**Comment by MikhailRyazanov** [comment]
Something very strange happens with Travis CI: for Python 3.10, instead of installing SciPy from a wheel package, like it [did before](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/588980288#L211-L212):
```
211 Collecting scipy
212  Downloading scipy-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
```
and currently does [for Python 3.9](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/590040514#L237-L238):
```
237 Collecting scipy
238   Downloading scipy-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
```
and [for Python 3.11](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/590040512#L212-L213):
```
212 Collecting scipy
213  Downloading scipy-1.9.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.4 MB)
```
now it [tries](https://app.travis-ci.com/github/PyAbel/PyAbel/jobs/590040513#L200-L201) to build *from source*:
```
200 Collecting scipy
201  Downloading scipy-1.9.3.tar.gz (42.1 MB)
```
and fails.  :–/ I've tried to restart the job, but got the same result.

Any ideas why this happens or where to ask/report? Or maybe just wait a couple of days and try again?

**Comment by DanHickstein** [comment]
Uhg, Travis being weird again. No, I have no idea why it's doing this. Waiting a day might be advisable...

**Comment by MikhailRyazanov** [comment]
The same problem today. Internet searches still give no relevant results. So I've decided to [ask](https://travis-ci.community/t/scipy-disappeared-from-python-3-10/13443) at the Travis CI Community Forums, maybe somebody would help... Otherwise, maybe we should just disable this build until the problem resolves?

By the way, Dan, how many minutes we have at Travis and  AppVeyor?

**Comment by DanHickstein** [comment]
Awesome! Thanks for asking Travis about the issue.

In the meantime, I'm happy to exclude Python 3.10 from the Travis tests for now and open a new issue to remind us to reinstate it.

On AppVeyor, I believe that we have (and have always had) unlimited build time. The issue is just that they only have one concurrent build, so it's a bit slow.

I tried to see how many credits we had left on Travis, but I couldn't figure it out. As far as I can tell, I no longer administer PyAbel on Travis, lol. I think that their support for Open Source has been going downhill. At some point in the near future, we may want to rethink which CI services we're using.

**Comment by MikhailRyazanov** [comment]
> As far as I can tell, I no longer administer PyAbel on Travis, lol.

This is really strange. :–)

So, as I understand, the plan is to make this pre-release now, then try to switch from Travis to GitHub Actions, make another pre-release to test how that works, and then finally release v0.9.0?
If so, could you please approve this PR? Because otherwise GitHub thinks that I'm merging my own PRs without any reviews...

**Review by DanHickstein — APPROVED** [review]

**Comment by DanHickstein** [comment]
Approved! 

I think that we should go ahead and release v0.9.0 and worry about the Travis issues later.

**Pull request merged**
