### PR TITLE
Appveyor fix

### PR DESCRIPTION
**Pull request by DanHickstein**
Trying to see if we can get Appveyor working again by calling "activate.bat" rather than setting the path manually, as discusesd in https://github.com/PyAbel/PyAbel/pull/257#issuecomment-506608835

### CODE REVIEW

**Comment by DanHickstein** [comment]
I got 
```
CALL "%PYTHON_ROOT%\\Scripts\\activate.bat"
The network path was not found.
```

**Comment by MikhailRyazanov** [comment]
I guess, in our case it should be `%MINICONDA%` instead of `%PYTHON_ROOT%`.

**Comment by DanHickstein** [comment]
You are now the appveyor expert :)

**Comment by DanHickstein** [comment]
I think that this can be merged now. Feel free to hit the green button.

**Comment by MikhailRyazanov** [comment]
Thanks! I'll then merge this.

**Pull request merged**
