### PR TITLE
Remove symmetric basex

### PR DESCRIPTION
**Pull request by DhrubajyotiDas**
This PR is related to #65 and #89. 

Briefly, the PyAbel codebase has a version of BASEX (call it **symmetric**) which accepts raw data with up/down symmetry (think of the letter B) and another version (**asymmetric**) which accepts raw data without this symmetry (think of the letter P). In the BASEX algorithm, raw data with up/down symmetry is *essentially* folded in half (i.e., the top and bottom halves are averaged), while raw data without up/down symmetry skips this step. Therefore, an equivalent result can be obtained by simply keeping the **asymmetric** code, and introducing a function to average the top and bottom halves when the user specifies that the raw data has up/down (or vertical) symmetry. This has the benefit of simplifying the codebase. 

In this PR, I've added a function to do the up/down averaging (I couldn't find an equivalent ready-made Numpy or Scipy function), and added a condition to the BASEX code which invokes this function when the `vertical_symmetry=True` parameter is passed to the basex function call. The rest is mostly cleanup of `basex.py` and `test_basex.py`. All code changes are on the backend; there should not be any UX changes.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Thanks for doing this @DhrubajyotiDas! 

I think that we already have the up/down averaging in the `tools.symmetry.get_image_quadrants` function. Are you planning (in this PR) to also modify basex to just accept a single quadrant?

**Comment by DhrubajyotiDas** [comment]
@DanHickstein I just pushed #95 for the single quadrant code.

**Comment by DhrubajyotiDas** [comment]
>I think that we already have the up/down averaging in the tools.symmetry.get_image_quadrants function. 

I hadn't realized that. I'll look to see if it is does what I intended with [updown_symmetry_rawdata()](https://github.com/DhrubajyotiDas/PyAbel/blob/remove-symmetric-basex/abel/tools/symmetry.py#L280), and if so, I'll modify this PR to reflect that.

If you think it's better to merge this first and file a separate PR for that, I'm okay with that as well, since I am fairly sure the code as-is is definitely functional (if a bit redundant).

**Comment by rth** [comment]
@DhrubajyotiDas  This looks good, and would definitely simplify things. 

So now there are this PR and PR #94  which modify pretty much the same `basex.py` file. Should we merge one and then look at the other?

**Pull request merged**
