### PR TITLE
Add unit tests for the centering function

### PR DESCRIPTION
**Pull request by rth**
This PR adds unit tests for the centering function as to solve the issue discussed in issue #34 . 

It adds following functions,
   -  `abel.tools.get_quadrants` :  a helper function to get the 4 quadrants of the image, as defined by @stggh implementation of Hassen&Law. The code is a bit different, but the result should be the same.
   - `abel.benchmark.is_symmetric`: checks that an image is symmetric, with respect to its center (both for odd and even images). The symmetry center is defined in the discussion of the issue #34.
   - `abel.tests.test_benchmark.test_symmetry_function`: some consistency tests for `is_symmetric`
   - `abel.tests.test_tools.test_centering_function_shape`: check that `center_image` preserves shape (for odd and even images)
   -  `abel.tests.test_tools.test_centering_function`: check that `center_image` centers the image correctly for both odd and even images.

With the current code base, 4 tests for the centering function do not pass (both in `test_centering_function_shape` and in `test_centering_function`), as can be seen in the [Travis CI logs](  https://travis-ci.org/PyAbel/PyAbel/jobs/93969224). This PR should be merged before PR #37, and those 4 failing tests should then be fixed by PR #37.

### CODE REVIEW

**Comment by stggh** [comment]
abel.tools.get_quadrants is a neat idea and your code is clever to include the an additional 1/2 pixel for odd size images. The extra 1/2 pixel will require a correction to the speed profile. (*)

Feature request:  add option   ,reorientate=True)
to deliver the quadrants with the correct orientation for use with iabel_hansenlaw_transform()
```
if reorientate:
    Q0 = np.fliplr(Q0)
    Q2 = np.flipud(Q2)
    Q3 = np.fliplr(np.flipud(Q3))
```

Also, is the following too obscure?
```
m_c = m%2 + m//2
n_c = n%2 + n//2
```

(*) The Hansen Law algorithm does not require a uniform sampling grid (last sentence on page 513 of article). I have not thought about the consequences. It is a matter of keeping track of the (0,Rmax) grid, or (0,vmax) speed grid, associated with the pixel image.

**Comment by stggh** [comment]
[Off topic - ignore if I should google the answer] 
Git - how do I merge @rth's tools.py with into my own fork without causing chaos in the final push merge of my fork into the master?  i.e. tools should be merged from @rth's fork, and only the hansenlaw stuff from my own.

**Comment by rth** [comment]
@stggh I updated the code with your suggestions.

As far as I understand, to merge this into you fork you have two options:
1. To use it right now, I think you can just merge this branch into yours. I believe you can do a PR from my fork to your on github.
2. If you wait a bit until this is merged into PyAbel master, a better solution, I think, would be to rebase your fork on the PyAbel master as to keep a clean git history without too many  merges. In our case, that would be [as explained in this post](https://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository),
   
    # Add the remote, call it "upstream":
    git remote add upstream git@github.com:PyAbel/PyAbel.git

    # Fetch all the branches of that remote into remote-tracking branches,
    # such as upstream/master:

    git fetch upstream

    # Make sure that you're on your master branch:

    git checkout master

    # Rewrite your master branch so that any commits of yours that
    # aren't already in upstream/master are replayed on top of that
    # other branch:

    git rebase upstream/master

more information about this can be found at [this link](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). I think for us it would be necessary to rebase anyway at some point before merging to master, as there is more and more parallel branches that sometimes change the same files.

**Comment by DanHickstein** [comment]
I think that we can go ahead and merge this. In American English, reorientate should be reorient, but we can leave reorientate in honor of @stggh's Australian nationality. :) I doubt that anybody will be confused.

**Pull request merged**
