### PR TITLE
Linbasex changes

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
These are the changes related to `linbasex` as discussed in #356, plus some other minor corrections (repair of `verbose` in `Transform()` and some corrections to the examples).

One thing that I'm not sure about is the docstring for `linbasex_transform()`. Previously it was shared with `linbasex_transform_full()` (see `_linbasex_parameter_docstring`), but there are in fact too many important differences for such mechanical treatment. Thus for `linbasex_transform()` I've simply documented its unique parameters and referred to the main function `linbasex_transform_full()` for the rest. But maybe every parameter must be documented for completeness? Or maybe it would be easier/better to replace them all with `**kwargs` and say that additional arguments are passed to `linbasex_transform_full()`, like we do in some other cases?

### CODE REVIEW

**Comment by stggh** [comment]
@MikhailRyazanov - excellent work on your part, thank you! 

I am testing and the results are a big improvement on the old code. 

Benchmark fails:
```python
(py310) [Gibbo:/home/stg121]$ ipython
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import abel

In [2]: abel.benchmark.AbelTiming(n=101, select=['linbasex'])
n = 101
  linbasex
    estimated ???---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 abel.benchmark.AbelTiming(n=101, select=['linbasex'])

File ~/.local/lib/python3.10/site-packages/PyAbel-0.8.5-py3.10-linux-x86_64.egg/abel/benchmark.py:276, in AbelTiming.__init__(self, n, select, repeat, t_min, t_max, verbose)
    274 self._vprint(' ', method)
    275 try:
--> 276     getattr(self, '_time_' + method)()
    277 except (KeyboardInterrupt, MemoryError) as e:
    278     self._vprint('\n' + repr(e) + '! Skipping the rest...')

File ~/.local/lib/python3.10/site-packages/PyAbel-0.8.5-py3.10-linux-x86_64.egg/abel/benchmark.py:347, in AbelTiming._skip.<locals>.decorator.<locals>.decorated(self)
    345     return
    346 else:  # otherwise run the benchmark
--> 347     f(self)
    348     # calculate the actual total time and report it
    349     t = (sum(self.res[k][m][-1] for k, m in res_keys) *
    350          self.repeat) / 1000  # [ms] -> [s]

File ~/.local/lib/python3.10/site-packages/PyAbel-0.8.5-py3.10-linux-x86_64.egg/abel/benchmark.py:472, in AbelTiming._time_linbasex(self)
    469 basis = linbasex.get_bs_cached(self.h, basis_dir=None)
    470 # benchmark the transform
    471 self._benchmark('inverse', 'linbasex',
--> 472                 linbasex._linbasex_transform_with_basis,
    473                 self.whole_image, basis)
    475 # discard all caches
    476 linbasex.cache_cleanup()

AttributeError: module 'abel.linbasex' has no attribute '_linbasex_transform_with_basis'
```

**Comment by MikhailRyazanov** [comment]
Thanks, @stggh! I thought that after implementing memory caching in #232, the internal `_linbasex_transform_with_basis()` became unnecessary, but forgot to check that it is still used in the benchmark code... Now I've replaced it with simply `linbasex_transform_full()`, as the overhead should be negligible.

**Comment by MikhailRyazanov** [comment]
I've added very basic unit tests for the benchmarks, to make sure that breaking them again will not go unnoticed. :–)

The tests coverage reporting was also behaving strangely, showing 0% and "No data was collected", supposedly because it was trying to collect it for the current `./abel` directory while using the system-installed `abel` package. Running `pytest` in a temporary directory solves this problem (maybe `cd tmp/` in `.travis.yml` tried to do so, but `tmp/` in fact means `./tmp`, which doesn't exist, so `cd` simply failed...), although the resulting file paths in the report look ugly. This apparently doesn't have a simple solution (https://github.com/pytest-dev/pytest/issues/569 is still open, without any recent activity) but, I guess, ugly paths are still better than useless "0%".

**Comment by stggh** [comment]
@MikhailRyazanov - good stuff. 

The `linbasex` transform radial profile is displaced by 1 pixel. This has been a long standing problem (although I cannot find the appropriate issue). Perhaps, your new insight might expose the soure:

linbasex-test3   gnome-shell-screenshot-gdqafc
 
```python

nm = 'Dribinski'
im = abel.tools.analytical.SampleImage(n=1001, name=nm).func

# projection
imp = abel.Transform(im, direction='forward', method='rbasex').transform

l = abel.Transform(imp, method='linbasex')
r = abel.Transform(imp, method='rbasex')
r_rad, r_beta = r.distr.rIbeta()[0], r.distr.Ibeta()[0]

# plot ---------------------------------------
fig, ax = plt.subplots()
ax.plot(l.radial, l.Beta[0], label='linbasex')
ax.plot(r_rad, r_beta/r_beta.max(), label='rbasex')

ax.legend(labelspacing=0.3, fontsize='small')
ax.set_xlabel('radius (pixels)')
ax.set_title(nm)

plt.savefig('linbasex-test3.svg')
plt.show()
```

**Comment by MikhailRyazanov** [comment]
It is indeed 1/2 pixel, not depending on `radial_step`, and for all radii. I don't see any potential problems in calculating the projections or solving the equations, so there is probably something in the basis. I've simplified the code a little bit, trying to understand what's going on, but still am not sure what causes this shift. The only thing that I suspect is that the basis assumes that whole pixels are covered, whereas the outer pixels (at _r<sub>k</sub>_ from the origin) must be only half-covered. So if I try instead of `np.tri(n)` [here](https://github.com/MikhailRyazanov/PyAbel/blob/6eeb256a039d6e1fac6ace07d461dcb6fee54b5d/abel/linbasex.py#L468-L469) to use `(np.tri(n) + np.tri(n, k=-1)) / 2`, this removes the shift but introduces some strange noticeable ringing when `radial_step=1` (although this works fine for sparse basis sets). Doesn't look like a good solution...

On the other hand, I've also noticed that the fact of applying smoothing, even negligible, can remove the shift when `Beta` length is even (that is, for example, working for `n=1001` but not for `n=1001+2`). Because the convolution with an even-sized array effectively shifts `Beta` values by a half-step. :–) So I've corrected this effect in the last commits, but it also suggests two possible solutions for the shift problem:
1. Shift the `radial` array by 0.5 pixel (and use it to create the image, because the image has the same problem). This is very simple but will always produce half-integer numbers in `radial`, which might cause other problems (for example, in comparisons with other methods).
2. “Shift” `Beta` values by interpolation (using `scipy.ndimage.shift()`). This will not affect the radii, pairs naturally with smoothing, and interpolation is used anyway to construct the output image, so it probably wouldn't harm `Beta`.

**Comment by MikhailRyazanov** [comment]
OK, `scipy.ndimage.shift()` actually works quite well, producing the speed distribution much more similar to other methods (can be seen better for smaller images, like `n=401`, where the peaks have fewer points). The anisotropy example and “Comparison of Transform Results” in the documentation also look more consistent. So I guess, this can be deemed as at least a temporary solution and definitely an improvement.

**Comment by stggh** [comment]
This is looking very good. I am still running a few more tests.

**Comment by stggh** [comment]
Sorry for the delay with my follow up, some reno jobs (painting) have been taking up my time. 

I am flummoxed  with `example_all_O2.py` which for some reason yields a displaced `linbasex` profile, whereas `example_all_dribinski.py` is all good. Simplified code, `linbasex-test6.py`, does not expose any issue between a single quadrant and the whole image transform.

Top image `example_all_O2.py` expanded, illustrating displacement of `linbasex` profile, bottom image `linbasex-test6.py` `linbasex` only (code below image):
image

```python
import numpy as np
import abel
import matplotlib.pyplot as plt

im = np.loadtxt('data/O2-ANU1024.txt.bz2')

imc = abel.tools.center.center_image(im, method='slice', square=True,
                                     radial_range=(370, 390))

# full image
l = abel.Transform(imc, method='linbasex')

# quadrant
q = abel.tools.symmetry.get_image_quadrants(imc)
lq, radial, speed, _ = abel.linbasex.linbasex_transform(q[0], return_Beta=True)
speed = speed[0]
rad, sp = abel.tools.vmi.angular_integration_3D(lq, origin=(-1, 0))

# plot 
plt.plot(radial, speed/speed.max(), label='quad.')
plt.plot(rad, sp/sp.max(), label='int.')
plt.plot(l.radial, l.Beta[0], label='full')
plt.legend()

plt.show()
```

BTW `example_all_dribinski.py` may now include `linbasex` as a method, since your changes to `linbasex` have made the result more comparable. However, `rbasex` cannot be included in this example because `rbasex_transform` returns additional parameters.

**Comment by MikhailRyazanov** [comment]
I suspect that the problem is in centering. Currently the image in `example_all_O2.py` is 1024×1023, which is not what `linbasex` expects. Adding `square=True` makes it 1023×1023 and the results better:

**original**
orig

**with `square=True`**
square

Then changing `method="slice"` to **`method="convolution"`** makes it even better:
conv
and, I would say, roughly (within the noise level) consistent with other methods.

So, I think, we should at least add `square=True`.

> BTW `example_all_dribinski.py` may now include `linbasex` as a method, since your changes to `linbasex` have made the result more comparable.

Yes, I was thinking why `example_all_dribinski.py` has fewer methods (`onion_bordas` is also missing) but left it alone. :–) But I can extend it. Maybe we then should also include `example_all_O2.py` in the documentation?

> However, `rbasex` cannot be included in this example because `rbasex_transform` returns additional parameters.

It's not difficult to make a “shim” for it (using `lambda` in the `transforms` dictionary), but the figure has no room for it anyway...

**Comment by stggh** [comment]
Yes, a square image is definitely required. Perhaps, `linbasex` should test that the image is square. 

The small remaining difference is now related to how well the real data image centre is defined, and the image distortion - so, all good.

Thanks, @MikhailRyazanov   

I will next review.

**Comment by MikhailRyazanov** [comment]
OK, I've added `square` to centering and changed the method to “convolution” for better results.
I've also changes the normalization such that it is the same for all methods, so that they show the same signal level, and the noise levels can be compared directly. For the speed distribution, the broader peaks are correspondingly lower as well (this also makes the plot slightly less messy).

> Perhaps, `linbasex` should test that the image is square.

It does. However, the quadrant obtained from `get_image_quadrants()` was indeed square (512 × 512), although the full image wasn't (1024 × 1023).

**Review by stggh — APPROVED** [review]
Excellent work @MikhailRyazanov, some essential, and overall, very nice improvements.

`linbasex` may also be added into `example_all_dribinsky.py`

```
diff example_all_dribinski.py ../../PyAbel-master/examples/.
26d25
<     "basex": abel.basex.basex_transform,
29d27
<     "linbasex": abel.linbasex.linbasex_transform,
30a29
>     "basex": abel.basex.basex_transform,
```
alphabetical order for the transform methods.

**Comment by MikhailRyazanov** [comment]
Thanks, @stggh!

> `linbasex` may also be added into `example_all_dribinsky.py`

I think, then it does something strange with combining the output image. So maybe simplify the whole example?
```python
# -*- coding: utf-8 -*-

# This example compares some available inverse Abel transform methods
# for the Dribinski sample image

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from time import time
import matplotlib.pylab as plt
import numpy as np

import abel

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

# inverse Abel transform methods -----------------------------
transforms = [
    "basex",
    "direct",
    "hansenlaw",
    "linbasex",
    "onion_peeling",
    "rbasex",
    "three_point",
    "two_point",
]
# number of transforms:
ntrans = len(transforms)

# sample image radius in pixels
R = 150

fIM = abel.tools.analytical.SampleImage(n=2 * R + 1, name="Dribinski").abel
# fIM += np.random.normal(0, 5000, fIM.shape)  # try adding some noise

print("image shape {}".format(fIM.shape))

# sectors for combining output images (clockwise from top)
row = np.arange(-R, R + 1)[:, None]
col = np.arange(-R, R + 1)
sector = np.asarray(ntrans * (1 - np.arctan2(col, row) / np.pi) / 2, dtype=int)

# apply each method --------------------

IM = np.zeros_like(fIM)  # for inverse Abel transformed images
ymax = 0  # max. speed distribution

for i, method in enumerate(transforms):
    print("\n------- {:s} inverse ...".format(method))
    t0 = time()

    # inverse Abel transform using 'method'
    recon = abel.Transform(fIM, method=method, direction="inverse",
                           symmetry_axis=(0, 1)).transform

    print("                    {:.4f} s".format(time()-t0))

    # copy sector to combined output image
    idx = sector == i
    IM[idx] = recon[idx]

    # method label for each quadrant
    annot_angle = 2 * np.pi * (0.5 + i) / ntrans
    annot_coord = (R + 0.8 * R * np.sin(annot_angle),
                   R - 0.8 * R * np.cos(annot_angle))
    ax1.annotate(method, annot_coord, color="white", ha="center")

    # polar projection and speed profile
    radial, speed = abel.tools.vmi.angular_integration_3D(recon)

    # plot speed distribution
    ax2.plot(radial, speed, label=method)

    # update limit
    ymax = max(ymax, speed.max())

plt.suptitle('Dribinski sample image')

ax1.set_title('Inverse Abel comparison')
vmax = IM[:, R+2:].max()  # ignoring pixels near center line
ax1.imshow(IM, vmin=0, vmax=0.1 * vmax)

ax2.set_title('Angular integration')
ax2.set_xlabel('Radial coordinate (pixel)')
ax2.set_xlim(0, 150)
ax2.set_ylabel('Integrated intensity')
ax2.set_ylim(-0.1 * ymax, 1.2 * ymax)
ax2.set_yticks([])
ax2.legend(ncol=2, labelspacing=0.1, frameon=False)

plt.tight_layout()
# plt.savefig('plot_example_all_dribinski.png', dpi=100)
plt.show()
```

**Comment by stggh** [comment]
Yes, very clever.

**Comment by MikhailRyazanov** [comment]
Done!

@DanHickstein, your turn. :–) Could you please check the affected documentation (`linbasex` module, examples, comparison) with fresh eyes?

**Review by DanHickstein — APPROVED** [review]
This all looks good to me! Great work @MikhailRyazanov and @stggh!

**Comment by MikhailRyazanov** [comment]
Thanks! Merging...

**Pull request merged**
