### PR TITLE
Changed readme to look good on GitHub (and PyPi)

### PR DESCRIPTION
**Pull request by DanHickstein**
In https://github.com/PyAbel/PyAbel/pull/135, I had formatted the links in the readme to look good on readthedocs.org. However, the readme can also be viewed directly on GitHub as well as whenever we make a release on PyPi: https://pypi.python.org/pypi/PyAbel. This limits the type of links that can be included in the readme.

(well, [there is a way around this](https://groups.google.com/forum/#!topic/sphinx-dev/bItey05hfFw), but it was too complicated for me to figure out)

For readthedocs.org (and any Sphinx documentation build), it's good to use links in the format
```rst
 :doc:`link text <file>`
```
However, this doesn't work with a simple RST interpreter like what is in place on GitHub or PyPi. So, the readme is a special document, and we can only use links in the standard RST format:
```
`link text <http://external.link/blah.html>`_
```
This makes me less inclined to include huge amounts of information in the readme (the readme should be reasonably short anyway). So, I moved the more detailed information about the transforms to `doc/transform_methods.rst`.

Now, I think the readme should look fine, both on github and on readthedocs.org. However, it still looks nicer on readthedocs (images are the correct size instead of being huge), so I included a note at the top referring people to the readthedocs.org.

You can check out how the readme will be rendered on GitHub over at my fork: 
https://github.com/DanHickstein/PyAbel/tree/fix-readme

### CODE REVIEW

**Comment by stggh** [comment]
@DanHickstein, nice work. The new look is fine, and the README.rst better with less detail.
1. It would be nice if the `transform methods` link opened in a new tab/window (target="_blank").
2. The readthedocs link, for hanselaw, has the old information, not current with the last PR #137. Will no doubt be fixed with a rebase.

**Comment by DanHickstein** [comment]
Thanks @stggh!

1. I tried for a while to figure out how to make a link open in a new window in an `.rst

2. The readthedocs build failed for some weird reason. I restarted it and it worked fine. There is a little green link in the lower left of the readthedocs page that lets you see more information and you can click on the "Builds" tab to make sure that things are working. 

https://readthedocs.org/projects/pyabel/builds/

**Comment by stggh** [comment]
Yes good to go.

@DanHickstein great work on all this doc stuff, they look fantastic. It has been very educational for me.

**Comment by DanHickstein** [comment]
> It has been very educational for me.

For me too! It's a confusing world out there, but I think that we are converging to something that look really, really good!

**Comment by stggh** [comment]
@DanHickstein I don't think that `readthedocs` is building (or the build is slow). The `transform` methods remain the old pages.

**Comment by DanHickstein** [comment]
I think that it's up-to-date. http://pyabel.readthedocs.org/en/latest/transform_methods/hansenlaw.html

Reload the page in your browser?

It has the new images:

image

**Comment by stggh** [comment]
Arrh! Your are right, the reload worked. Sorry, about that!

**Comment by DanHickstein** [comment]
no prob :)

**Pull request merged**
