### PR TITLE
Making the GUI example work again

### PR DESCRIPTION
**Pull request by DanHickstein**
This PR contains a few tweaks to make the GUI example successfully run. While we should make the GUI much better, I thought that I would start by making the existing GUI example actually work, since it's currently broken.

### CODE REVIEW

**Comment by DanHickstein** [comment]
Good call. I made those changes and then made the examply_GUI.py mostly pep8 compliant just to test my pep8-ing skills :)

**Comment by stggh** [comment]
All good. 

Since you are on a roll, don't forget to apply the same changes to `example_simple_GUI.py`  ;-)

**Comment by DanHickstein** [comment]
Oh, I forgot that there was a simple GUI! I made similar changes to that one too. :)

**Comment by stggh** [comment]
Thanks, good work. Both GUI examples work well, within their programming limitations.

There is a little more styling required for `example_simple_GUI.py`:
```python
[Gibbo:.+UI_fun/examples]$ pycodestyle example_simple_GUI.py 
example_simple_GUI.py:111:27: E231 missing whitespace after ','
example_simple_GUI.py:111:80: E501 line too long (100 > 79 characters)
example_simple_GUI.py:113:8: E111 indentation is not a multiple of four
example_simple_GUI.py:113:26: E231 missing whitespace after ','
example_simple_GUI.py:113:80: E501 line too long (81 > 79 characters)
example_simple_GUI.py:194:46: W605 invalid escape sequence '\p'
example_simple_GUI.py:208:21: E116 unexpected indentation (comment)
```

**Comment by MikhailRyazanov** [comment]
Seems to work in Python 3 under Debian.

Python 2 cannot find some modules (they were renamed between Python 2 and Python 3). If we want to drop Python 2 support completely, then the rest (`if sys.version_info[0] < 3:`) should be removed also. Otherwise these renamed imports should go into the same version selector. Or maybe [six](https://six.readthedocs.io/) might help (I did not use it myself, but saw it among packages installed on my system, so it's probably not uncommon).

BTW, “center image” does trigger a deprecation warning. ;–) If you want to merge this PR after #267, the names there will need to be updated also (I did not, since the whole example was not working at all), otherwise I will need to update them in #267 after this is merged.

**Comment by stggh** [comment]
I believe PR's are with respect to the current origin (master).

I am in favour of dropping python2 support, to allow cleaning of the header baggage for each python file:
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
# testing strings with Python 2 and 3 compatibility
from six import string_types
```

**Comment by MikhailRyazanov** [comment]
Since I don't use PyAbel myself, I don't really care about Python 2 support, but just dropping it for no good reason does not look nice...

@DanHickstein, I forgot that `six` is already used in some files, so we _can_ rely on it.

Basically, if you replace all `tkinter`-related imports (including the whole `import sys` + `if` part) with
```
from six.moves import tkinter as tk
from six.moves import tkinter_ttk as ttk
from six.moves import tkinter_font as tkFont
from six.moves import tkinter_scrolledtext as scrolledtext
from six.moves import tkinter_tkfiledialog as filedialog
```
(and change `ScrolledText()` and `askopenfilename()` calls accordingly), then everything starts working fine in both Python 2 and 3.

Dropping Python 2 later will require only removing “`from six.moves `” prefixes and replacing `_` by `.`.

**Comment by DanHickstein** [comment]
Thanks guys! 

Here is an update which addresses the remaining pep8 issues (except for a few "line too long" that I don't intend to fix).

I also used the `from six.moves` code from @MikhailRyazanov, which works great. These examples seem to work with both py2 and py3 on OSX.

Regarding py2 compatibility, we can discuss more over on this issue:

https://github.com/PyAbel/PyAbel/issues/221

I don't have a good sense of what fraction of python users are still on py2. But, I would probably wait another 6 months or so before we actively remove any py2 support. (Heck, I've only been using py3 for a few months :) )

**Comment by MikhailRyazanov** [comment]
Thanks, @DanHickstein! Please add something to the changelog and merge this. I'll then update the centering part in #267.

**Comment by DanHickstein** [comment]
Okay, I added a sentence in the changelog about this. I'll go ahead and merge now!

**Pull request merged**
