### PR TITLE
Removed "import abel"

### PR DESCRIPTION
**Pull request by DanHickstein**
As suggested in https://github.com/PyAbel/PyAbel/issues/140, I removed the `import abel` from `benchmark.py` and `transform.py` and replaced with
```
from . import basex
from . import hansenlaw
from . import direct
from . import three_point
from . import tools
```

This allows the PyAbel package to be run from its directory without installing the package.

I’m not completely sure if we want to do this, but I’ve made the changes in order to spark the discussion. 

@PyAbel/developers, @himbeles

### CODE REVIEW

**Comment by ldes89150** [comment]
I think it's a right decision.

**Comment by stggh** [comment]
Does not appear to work (not installed):
```python
[etalon:.+n/VMI/PyAbel-DH]$ git clone https://github.com/DanHickstein/PyAbel.git -b imports
Cloning into 'PyAbel'...
remote: Counting objects: 3234, done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 3234 (delta 103), reused 0 (delta 0), pack-reused 3059
Receiving objects: 100% (3234/3234), 19.88 MiB | 3.62 MiB/s, done.
Resolving deltas: 100% (2247/2247), done.
Checking connectivity... done.
[etalon:.+n/VMI/PyAbel-DH]$ cd PyAbel
[etalon:.+yAbel-DH/PyAbel]$ cd abel
[etalon:.+-DH/PyAbel/abel]$ python benchmark.py 
Traceback (most recent call last):
  File "benchmark.py", line 9, in <module>
    from . import basex
ValueError: Attempted relative import in non-package

``

**Comment by DanHickstein** [comment]
I think that it works installed (it works on Travis and Appveyor). And try `cd ..` (Back up to /PyAbel-DH) and `import abel`.

**Comment by DanHickstein** [comment]
Yeah, this does take away our ability to `python bechmark.py` and include stuff in `main()`. But this is probably sloppy anyways.

**Comment by stggh** [comment]
Ok, appears to work.   

Perhaps, add running instructions at the head of  `benchmark.py` (I think that  this file should live in the `tools` directory in any case (#113)), or, probably not a good option, add another file in the `abel` directory, `run_benchmark.py` with 
```python
import abel
abel.benchmark.AbelTiming()
```

**Comment by DanHickstein** [comment]
Are you a fan of the tools directory? To me, I kinda prefer a flat organization so that I don't need to type `.tools.` when I'm calling functions...

**Comment by stggh** [comment]
Only in the sense that it keeps the core transform programs neatly separate from the auxiliary code.

**Comment by DanHickstein** [comment]
Yeah, I like the way that the folders separate the source code, but I don't like typing more lines. 

Anyway, I think that we can merge this.

**Pull request merged**
