### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by DhrubajyotiDas**
Following up from the discussions in #25 and a few other places (ye olde PR #10 by @rth)

* Edited a lot of the user-facing code to conform to [PEP8](https://www.python.org/dev/peps/pep-0008/). Many of these edits fixed a lot of issues with the Sphinx auto-doc build.
* PEP8 compliance was verified by running
```
pip install pep8
pep8 --show-source --show-pep8 path\to\file.py
```
* Running `make html` now gives about 16 warnings (it started at around 57 warnings prior to this PR)
* For some reason, the `abel.analytical` module docstrings never update, no matter what I do to them. Strange behavior, @DanHickstein 
* I plan on digging into Sphinx a bit more to see what's up, but for now, this code can be safely merged, and the Sphinx relevant changes taken care of in a different PR.

If I may suggest an edit to `contribution.md`: we could consider asking the contributors to make their PRs PEP8 compliant so we don't end up undoing this in the future as the code grows.

### CODE REVIEW

**Comment by DanHickstein** [comment]
@DhrubajyotiDas, thanks for doing this! Look great! 

I'm in the airport, so can't look too carefully right now, but as far as the abel.analytical goes, I think that might be a hold-over from generating the original documentation when `analytical.py` was in /abel and not in /abel/tools, where it lives now. Maybe you can edit the `abel.rst

**Comment by DhrubajyotiDas** [comment]
Thanks for the tip, @DanHickstein. `analytical.py` docstrings are now responsive, total errors down to 15. I've attached the terminal output when I try to build the docs now in the hopes that someone can point out the next breakthrough.

```terminal
Dhrubajyoti Das@DhrubajyotiDas /cygdrive/e/My Documents/PyAbel/doc
$ make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Parameters:
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Returns:
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section To Do
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Transform Methods
  warn("Unknown section %s" % key)
E:\My Documents\PyAbel\abel\tools\center.py:27: UserWarning: Integer center detected, but not respected.treating center as float and interpolating!
  warnings.warn('Integer center detected, but not respected.'
reading sources... [100%] modules
E:\My Documents\PyAbel\doc\abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
E:\My Documents\PyAbel\abel\tools\analytical.py:docstring of abel.tools.analytical.abel_step_analytical:19: WARNING: Literal block expected; none found.
[u'parse_matlab_basis_sets(path)', u':module: abel.tools.io', u'', u'', u'', u'Load matlab generated basis sets files,', u'', u'The expected format for the `path` argument is a string of the form', u'"some_basis_set_{}_1.bsc" where "{}" will be replaced by "" for', u'the first file and "pr" for the second. Gzip compressed text files', u'are accepted. For instance:', u'     basis1000_1.bst.gz', u'     basis1000pr_1.bst.gz']:9: ERROR: Unexpected indentation.
docstring of abel.transform.transform:25: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:59: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:95: ERROR: Inconsistent literal block quoting.
docstring of abel.transform.transform:101: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:104: ERROR: Inconsistent literal block quoting.
docstring of abel.transform.transform:110: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:113: ERROR: Inconsistent literal block quoting.
[u"transform(IM, direction=u'inverse', method=u'three_point', center=u'none', verbose=True, vertical_symmetry=True, horizontal_symmetry=True, use_quadrants=(True, True, True, True), transform_options={}, center_options={})", u':module: abel.transform', u'', u'', u'', u'transform - the go-to function for all of your Abel transform needs!!', u'', u'This performs the forward or reverse Abel transform         using a user-selected method.', u'', u':Parameters:', u'', u'    **IM** : a NxM numpy array', u'', u'        This is the image to be transformed', u'', u'    **direction** : str', u'', u'        The type of Abel transform to be performed.', u'        ', u"        'forward' :", u"            A 'forward' Abel transform takes a (2D) slice of a 3D image", u'            and returns the 2D projection.', u"        'inverse' :", u"            An 'inverse' Abel transform takes a 2D projection and reconstructs", u'            a 2D slice of the 3D image.', u"        The default is 'inverse'.", u'', u'
  **method** : str', u'', u'        specifies which numerical approximation to the Abel transform', u'        should be employed (see below). The options are', u'        ', u"        'hansenlaw' :", u'            the recursive algorithm described by Hansen and Law', u"        'basex' :", u'            the Gaussian "basis set expansion" method of Dribinski et al.', u"        'direct' :", u'            a naive implementation of the analytical formula by Roman Yurchuk.', u"        'three_point' :", u'
           the three-point transform of Dasch and co-workers', u'', u'    **center** : tuple or str', u'', u'        If a tuple (float, float) is provided, this specifies', u'        the image center in (y,x) (row, column) format.', u'        A value `None` can be supplied', u'        if no centering is desired in one dimension,', u"        for example 'center=(None, 250)'.", u'        If a string is provided, an automatic centering algorithm is used', u'        ', u"        'image_center' :", u'
         center is assumed to be the center of the image.', u"        'by_slice' :", u'            (whatever this does)', u"
      'com' :", u'            the center is calculated as the center of mass', u"        'none' :", u'             No centering is performed. An image with an odd', u'             number of columns must be provided.', u"        The default is 'none'.", u'', u'    **verbose** : boolean', u'', u'        True/False to determine if non-critical output should be printed.', u'', u'
    **vertical_symmetry** : boolean', u'', u'        Symmetrize the image in the up/down direction?', u'        (The first axis is the vertical axis.)', u'', u'    **horizontal_symmetry** : boolean', u'', u'        Symmetrize the image in the left/right direction?', u'', u'    **use_quadrants** : boolean tuple (Q0,Q1,Q2,Q3)', u'', u'         select quadrants to be used in the analysis.', u'         The quadrants are numbered starting from', u'         Q0 in the upper right and proceeding counter-clockwise:', u'        ', u'         ::', u'        ', u'              +--------+--------+', u'              | Q1   * | *   Q0 |', u'              |   *    |    *   |', u'              |  *     |     *  |                               AQ1 | AQ0', u'
        +--------o--------+ --(inverse Abel transform)--> ----o----', u'              |  *     |     *  |
          AQ2 | AQ3', u'              |   *    |    *   |', u'              | Q2  *  | *   Q3 |          AQi == inverse Abel transform', u'              +--------+--------+                 of quadrant Qi', u'        ', u'        ::', u'        ', u'
     (1) vertical_symmetry = True', u'        ::', u'        ', u'            Combine:  `Q01 = Q1 + Q2, Q23 = Q2 + Q3`', u'
         inverse image   AQ01 | AQ01', u'                            -----o-----', u'                            AQ23 | AQ23', u'        ::', u'        ', u'        (2) horizontal_symmetry = True', u'        ::', u'        ', u'            Combine: Q12 = Q1 + Q2, Q03 = Q0 + Q3', u'            inverse image   AQ12 | AQ03', u'                            -----o-----', u'
                    AQ12 | AQ03', u'        ::', u'        ', u'        (3) vertical_symmetry = True, horizontal = True', u'
      ::', u'        ', u'            Combine: Q = Q0 + Q1 + Q2 + Q3', u'            inverse image   AQ | AQ', u'
               ---o---  all quadrants equivalent', u'                            AQ | AQ', u'        ', u'', u'    **transform_options** : tuple', u'', u'        Additional arguments passed to the individual transform functions.', u'        See the documentation for the individual transform method for options.', u'', u'    **center_options** : tuple', u'', u'        Additional arguments to be passed to the centering function.', u'', u':Returns:', u'', u'    **results** : dict', u'', u'        The transform function returns a dictionary of results', u'        depending on the options selected', u"            - results['transform']", u'                (always returned) is the 2D forward/reverse Abel transform', u"            - results['radial_intensity']", u'                is not currently implemented', u"            - results['residual']", u'                is not currently implemented']:133: ERROR: Unexpected indentation.
E:\My Documents\PyAbel\doc\abel.rst:92: WARNING: autodoc: failed to import class u'AbelTransform' from module u'abel.transform'; the following exception was raised:
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "c:\anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "c:\anaconda\lib\site-packages\sphinx\util\inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: AbelTransform
E:\My Documents\PyAbel\doc\abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
looking for now-outdated files... none found
pickling environment... done
checking consistency... E:\My Documents\PyAbel\doc\modules.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] modules
generating indices... genindex py-modindex
highlighting module code... [100%] abel.three_point
writing additional pages... search
copying images... [100%] _build/examples/example_hansenlaw_Xe.png
copying static files... WARNING: html_static_path entry u'E:\\My Documents\\PyAbel\\doc\\_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 15 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by stggh** [comment]
Try adding a `::` at line 96 in `abel.transform.py`, just above `transform options`:
```python
       (3) vertical_symmetry = True, horizontal = True
       :: 
    
           Combine: Q = Q0 + Q1 + Q2 + Q3
           inverse image   AQ | AQ       
                           ---o---  all quadrants equivalent
                           AQ | AQ
       ::

    transform_options : tuple
```

My doc build attempted to build something for `abel.transform.AbelTransform  Class`, legacy stuff left in `abel.rst`, that should be removed.

**Comment by DhrubajyotiDas** [comment]
@stggh Removing `abel.transform.AbelTransform Class` and the `::` in `transform.py` helped clean up two of the warnings. Thanks.

**Comment by stggh** [comment]
Crap, only 2!   I have cloned your fork.  My Mac set-up cannot handle 'numpydocs', so I commented from `conf.py`.

This is the output generated. How do you want to work through this list, so that we do not duplicate effort?
```python
[Steve:.+l-DB/PyAbel/doc]$ !make
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.4
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/center.py:27: UserWarning: Integer center detected, but not respected.treating center as float and interpolating!
  warnings.warn('Integer center detected, but not respected.'
reading sources... [100%] modules                                               
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.absolute_ratio_benchmark:5: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.absolute_ratio_benchmark:8: ERROR: Unexpected indentation.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.is_symmetric:4: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.is_symmetric:7: ERROR: Unexpected indentation.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.is_symmetric:8: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/benchmark.py:docstring of abel.benchmark.is_symmetric:12: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/direct.py:docstring of abel.direct.fabel_direct:12: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/direct.py:docstring of abel.direct.fabel_direct:37: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/direct.py:docstring of abel.direct.iabel_direct:11: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/direct.py:docstring of abel.direct.iabel_direct:36: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.fabel_hansenlaw:44: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.fabel_hansenlaw:69: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.hansenlaw_transform:45: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.hansenlaw_transform:70: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.iabel_hansenlaw:44: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/hansenlaw.py:docstring of abel.hansenlaw.iabel_hansenlaw:69: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.three_point.get_bs_three_point_cached:9: SEVERE: Unexpected section title.

Parameters
----------
docstring of abel.three_point.iabel_three_point:7: SEVERE: Unexpected section title.

Parameters
-----------
docstring of abel.three_point.iabel_three_point:25: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.three_point.iabel_three_point_transform:5: SEVERE: Unexpected section title.

Parameters
----------
docstring of abel.three_point.iabel_three_point_transform:10: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.basex.basex_transform:7: SEVERE: Unexpected section title.

Parameters
----------
docstring of abel.basex.basex_transform:17: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.basex.get_bs_basex_cached:8: SEVERE: Unexpected section title.

Parameters:
-----------
docstring of abel.basex.get_bs_basex_cached:19: SEVERE: Unexpected section title.

Returns:
--------
docstring of abel.basex.iabel_basex:8: SEVERE: Unexpected section title.

Parameters
----------
docstring of abel.basex.iabel_basex:28: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.abel_step_analytical:15: WARNING: Literal block expected; none found.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.abel_step_analytical:18: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.abel_step_analytical:28: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.sample_image:4: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.sample_image:20: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/io.py:docstring of abel.tools.io.parse_matlab_basis_sets:7: ERROR: Unexpected indentation.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.fit_gaussian:4: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.fit_gaussian:9: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.gaussian:8: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.gaussian:25: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.gradient:8: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.gradient:21: SEVERE: Unexpected section title.

Returns
-------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.gradient:26: SEVERE: Unexpected section title.

To do
-----
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.guss_gaussian:4: SEVERE: Unexpected section title.

Parameters
----------
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/math.py:docstring of abel.tools.math.guss_gaussian:9: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.transform.transform:8: SEVERE: Unexpected section title.

Parameters
----------
docstring of abel.transform.transform:20: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:50: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:85: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:95: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:105: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:107: WARNING: Literal block expected; none found.
docstring of abel.transform.transform:114: SEVERE: Unexpected section title.

Transform Methods
-----------------
docstring of abel.transform.transform:168: SEVERE: Unexpected section title.

Returns
-------
docstring of abel.transform.transform:172: ERROR: Unexpected indentation.
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/stg121/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/modules.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] modules                                                
generating indices... genindex py-modindex
highlighting module code... [100%] abel.three_point                             
writing additional pages... search
copying images... [100%] _build/examples/example_hansenlaw_Xe.png               
copying static files... WARNING: html_static_path entry u'/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 56 warnings.

Build finished. The HTML pages are in _build/html.
```

**Comment by DhrubajyotiDas** [comment]
I compared your output to mine, and the following common errors popped out - my hunch is fixing these should be first priority. First code block is your errors, second is mine. 

Apart from that, the rest of your errors come from not having `numpydocs`. I had the exact same issues before getting `numpydocs`, and those went away afterwards.

I suggest we both work on this, and either of us hit upon a solution to any of these errors, we post here. I'll keep pushing updates to the PR. 

1.
```python
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
```
```
E:\My Documents\PyAbel\doc\abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
```

2.
```python
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/abel/tools/analytical.py:docstring of abel.tools.analytical.abel_step_analytical:15: WARNING: Literal block expected; none found.
```
```
E:\My Documents\PyAbel\abel\tools\analytical.py:docstring of abel.tools.analytical.abel_step_analytical:19: WARNING: Literal block expected; none found.
```

3.
```python
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/stg121/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
```
```
E:\My Documents\PyAbel\doc\abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
```

4.
```python
checking consistency... /Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/modules.rst:: WARNING: document isn't included in any toctree
```
```
checking consistency... E:\My Documents\PyAbel\doc\modules.rst:: WARNING: document isn't included in any toctree
```

5.
```python
docstring of abel.transform.transform:20: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:50: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:85: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:95: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:105: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:107: WARNING: Literal block expected; none found.
```
```
docstring of abel.transform.transform:26: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:60: WARNING: Definition list ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:103: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:113: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:123: WARNING: Literal block ends without a blank line; unexpected unindent.
docstring of abel.transform.transform:125: WARNING: Literal block expected; none found.
```

**Comment by DhrubajyotiDas** [comment]
Solution to Issue 4.
```python
checking consistency... /Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/modules.rst:: WARNING: document isn't included in any toctree
```
```
checking consistency... E:\My Documents\PyAbel\doc\modules.rst:: WARNING: document isn't included in any toctree
```

Deleted `modules.rst`

**Comment by DhrubajyotiDas** [comment]
Solution to Issue 3.
```python
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/stg121/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
```
```
E:\My Documents\PyAbel\doc\abel.lib.rst:10: WARNING: autodoc: failed to import module u'abel.lib.direct'; the following exception was raised:
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named direct
```

Delete from `abel.lib.rst`
```
Submodules
----------

abel.lib.direct module
----------------------

.. automodule:: abel.lib.direct
    :members:
    :undoc-members:
    :show-inheritance:
```

**Comment by DhrubajyotiDas** [comment]
Fix for Issue 1.
```python
/Users/stg121/Software/Python/VMI/PyAbel-DB/PyAbel/doc/abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
```
```
E:\My Documents\PyAbel\doc\abel.rst:7: WARNING: toctree contains reference to nonexisting document u'abel.tests'
```
Added file `abel.tests.rst`

**Comment by stggh** [comment]
@DhrubajyotiDas you are a machine.

Issue 2.
The `Literal block` errors appear to be indenting **and** only one `::` required (despite my comment above). `abel.tools.analytica.abel_step_anaytical()` remove the lower `::`

```python
def abel_step_analytical(r, A0, r0, r1):
    """
    Directed Abel transform of a step function located between r0 and r1,
    with a height A0
    ::


          A0 +                  +-------------+
             |                  |             |
             |                  |             |
           0 | -----------------+             +-------------
             +------------------+-------------+------------>
             0                  r0            r1           r axis


    This function is mostly used for unit testing the inverse Abel transform
```

**Comment by DhrubajyotiDas** [comment]
@stggh Thanks for the tips! All warnings taken care of now!

```
Dhrubajyoti Das@DhrubajyotiDas /cygdrive/e/My Documents/PyAbel/doc
$ make clean html
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: 11 added, 0 changed, 0 removed
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Parameters:
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Returns:
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Transform Methods
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section Paramters
  warn("Unknown section %s" % key)
c:\anaconda\lib\site-packages\numpydoc\docscrape.py:136: UserWarning: Unknown section To Do
  warn("Unknown section %s" % key)
E:\My Documents\PyAbel\abel\tools\center.py:27: UserWarning: Integer center detected, but not respected.treating center as float and interpolating!
  warnings.warn('Integer center detected, but not respected.'
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex
highlighting module code... [100%] abel.three_point
writing additional pages... search
copying images... [100%] _build/examples/example_hansenlaw_Xe.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/html.
```

**Comment by stggh** [comment]
@DhrubajyotiDas well done you deserve a gold medal for that effort.

**Comment by DhrubajyotiDas** [comment]
The skeleton should be error-free now. Given my lack of Sphinx knowledge, I undoubtedly messed up some of the actual doc content, but we should be able to edit that in easily now.

Thanks for your help @stggh!

**Comment by DanHickstein** [comment]
Great work guys!! I'm away this weekend, so it was great to check my email
on my phone and see so many improvements!

On Friday, February 19, 2016, Dhrubajyoti Das <notifications@github.com>
wrote:

> The skeleton should be error-free now. Given my lack of Sphinx knowledge,
> I undoubtedly messed up some of the actual doc content, but we should be
> able to edit that in easily now.
>
> Thanks for your help @stggh <https://github.com/stggh>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAbel/PyAbel/pull/102#issuecomment-186463671>.
>


-- 
Daniel D. Hickstein
DanHickstein@gmail.com
Phone: 301 787 1853

**Comment by DanHickstein** [comment]
Scanning quickly through the heroic volume of changes (great work @DhrubajyotiDas and @stggh!!), this looks all good to me! Any reason not to click the big green button?

**Comment by DhrubajyotiDas** [comment]
No, I think we can go ahead with the merge.

**Comment by DhrubajyotiDas** [comment]
Thanks for the feedback @stggh and @DanHickstein!

**Comment by DanHickstein** [comment]
Great work!!

**Pull request merged**
