### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by DhrubajyotiDas**
This PR fixes the `basex` step example. 

figure_1

@DanHickstein Do you want me to reduce the `example_hansenlaw_basex.py` size to `n=301` in this PR as well?

### CODE REVIEW

**Comment by DanHickstein** [comment]
>Do you want me to reduce the example_hansenlaw_basex.py size to n=301 in this PR as well?
yes please!

And can you fix the PEP8 thing that you found with the previous (merged) PR?

**Comment by DanHickstein** [comment]
And this looks good to me if you want to merge.

**Comment by DhrubajyotiDas** [comment]
I'll bring the codebase to PEP8 and fix the `n=301` issue and then merge this.

**Comment by DhrubajyotiDas** [comment]
@DanHickstein Does #125 fix the `n=301` issue or is that still on the table? I had do a bit of rebasing (oh the horror!) and I think I've got everything straightened out...

**Comment by DanHickstein** [comment]
Ha! Sorry for the rebase disaster. No, I didn't mess with the n=301. You can probably just go ahead and merge this and I will get the n=301. I'm making some other changes to the docs at the moment.

**Pull request merged**
