### PR TITLE
abel/tools/analytical.py sample_image_dribinski() code correction as per #70

### PR DESCRIPTION
**Pull request by stggh**
Code correction to the BASEX paper sample image function `abel.tools.analytical.sample_image_dribinski()` as per discussion issue #70.

*to do: add parameters to set image center, and provide for even image size*

### CODE REVIEW

**Comment by DanHickstein** [comment]
Hmmm, now center_image_by_slice is failing the test. Perhaps the test is not entirely accurate. Since we are starting with an odd image, if we shift it by 2 pixels, then I think that the offset is maybe only 1.5 pixels....

I'm looking at lines 19-29 of `test_tools_vmi.py`:
```python
    # image width, height n = 361
    IM = sample_image_dribinski()
    
    # artificially displace center
    IMx = shift(IM, (-1,2))

    # find vertical center
    # radial range limits comparison to smaller radial range
    IMy, offset = find_image_center_by_slice(IMx, radial_range=(5,120), axis=1)

    assert np.allclose(offset, (0,-2), rtol=0, atol=0.1)
```

**Comment by DanHickstein** [comment]
This is weird: when I try to run 
``python  -c "import abel.tests; abel.tests.run_cli(coverage=True)"`` on this branch, it runs all of the tests except for the ``abel.tests.test_tools_vmi.test_vmi_find_image_center`` test that is failing on TravisCI. I thought that all of the tests scripts in the ``tests`` folder would be run. And I don't understand why they would be run on TravisCI and not on my computer. 

Any ideas @rth?

**Comment by stggh** [comment]
@DanHickstein, @rth, bug in `axis_slices` (= vertical, and horizontal slices), poor/rushed coding gave incorrect slice sizes (`top, bottom, left, right`), and the image was not cut through the center column/row. The messy code is working. I will look at it in more detail once I return from the beach (on Sunday).

**Comment by DanHickstein** [comment]
Thanks @stggh! 

Do you want me to merge this PR, or keep it open as a reminder to take a look at the "messy" code?

**Comment by stggh** [comment]
Keep the PR open and I will revisit it early next week. Tks

**Comment by stggh** [comment]
Sorry for the delay, I am still tracking the issue with single quadrant image vs whole image processing:
whole_vs_quad
```python
#!/usr/bin/env python

from __future__ import division
import numpy as np

from abel.hansenlaw import iabel_hansenlaw_transform, iabel_hansenlaw,\
                           fabel_hansenlaw_transform
from abel.tools.analytical import sample_image_dribinski
from abel.tools.symmetry import get_image_quadrants, put_image_quadrants
from abel.tools.vmi import calculate_speeds
import matplotlib.pyplot as plt

# BASEX sample image  361x361
IM = sample_image_dribinski()

Q = get_image_quadrants(IM, reorient=True)

# forward transform
FQ = []
for q in Q:
    FQ.append(fabel_hansenlaw_transform(q))

# recreate image - use single quadrant Q0 to generate whole image
FIM = put_image_quadrants((FQ[0], FQ[1], FQ[2], FQ[3]), odd_size=True)

# whole image transform
AFIM = iabel_hansenlaw(FIM)
wspeed, wr = calculate_speeds(AFIM)

#single quadrant transform
AFQ0 = iabel_hansenlaw_transform(FQ[0])
qspeed, qr = calculate_speeds(AFQ0, origin=(0,0))

plt.plot(wr, wspeed, 'r-', label="whole image inversion")
plt.plot(qr, qspeed, 'b-', label="singe Q0 quadrant inversion")
plt.legend()

plt.savefig("whole_vs_quad.png", dpi=150)
plt.show()
```

PS: @DanHickstein, @rth, @DhrubajyotiDas  - you all appear to have gone quiet. Any progress on standardizing the `BASEX` interface, `onion_peeling` Q0 processing,  docs ...  ;-)

**Comment by DanHickstein** [comment]
Thanks for this @stggh! So, there is still an issue?

And yes, I have become busy with a new job and haven't been able to spend as much time on PyAbel as it deserves. But you are correct, we should make a final push to get the code documented, cleaned up, and ready for public consumption. I would love to post an announcement to the [Molecular Dynamics mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=MOLECULAR-DYNAMICS-NEWS) (and anywhere else where people would be interested) and let them know about PyAbel and that they should start using it an improving it.

But, before we do that, we should get the documentation in working order and make the package look professional. Basically, the 1.0 release. I will try to put in some more time on this in the next few weeks.

**Comment by stggh** [comment]
Yes, the single quadrant vs all quadrant analysis is inconsistent. It should not take too long to track the problem down.

**Comment by stggh** [comment]
2D Gaussian analysis indicates the inconsistencies may be a due to accumulated errors in the Hansen and Law inverse Abel transform which are exaggerated by the small size `n=361` of the BASEX samle image. Here is the 2D Gaussian for `n=1001`
whole_vs_quad

```python
#!/usr/bin/env python

from __future__ import division
import numpy as np

from abel.hansenlaw import iabel_hansenlaw_transform, iabel_hansenlaw,\
                           fabel_hansenlaw_transform
from abel.tools.analytical import sample_image_dribinski
from abel.tools.symmetry import get_image_quadrants, put_image_quadrants
from abel.tools.vmi import calculate_speeds
import matplotlib.pyplot as plt

# BASEX sample image  361x361
#IM = sample_image_dribinski()

n = 1001
n2 = n//2
x = np.linspace(-n2, n2, n)
X, Y = np.meshgrid(x, x)

# 2D Gaussian intensity distribution
IM = np.exp(-(X*X+Y*Y)/n/50)

# raw speed distribution
rspeed, rr = calculate_speeds(IM)

Q = get_image_quadrants(IM, reorient=True)

# forward transform
FQ = []
for q in Q:
    FQ.append(fabel_hansenlaw_transform(q))

# recreate image - use single quadrant Q0 to generate whole image
FIM = put_image_quadrants((FQ[0], FQ[1], FQ[2], FQ[3]), odd_size=True)

# whole image transform
AFIM = iabel_hansenlaw(FIM)
wspeed, wr = calculate_speeds(AFIM)

#single quadrant transform
AFQ0 = iabel_hansenlaw_transform(FQ[0])
qspeed, qr = calculate_speeds(AFQ0, origin=(0,0))

plt.plot(rr, rspeed, 'k--', label="original image")
plt.plot(wr, wspeed, 'r-', label="whole image inversion")
plt.plot(qr, qspeed*2, 'b-', label="singe Q0 quadrant inversion")
plt.legend()
plt.title("2D Gaussian")

plt.savefig("whole_vs_quad.png", dpi=150)
plt.show()
```

I am not sure why there is a factor of x2 (not x4) for the single quadrant speed intensity.

The 2D Gaussian suggests all is well. The 4 quadrant whole image inverse Abel transform may accumulate more noise/uncertainty.  I will investigate how 1 quadrant vs 4 combined quadrants in to one compare (later).

**Comment by stggh** [comment]
There was no need to examine the 2D Gaussian, simply, setting `n=1001` in `sample_image_dribibksi(n=1001)` improves the comparison considerably:
whole_vs_quad

So the problem was one of sample size.

There is a remaining issue with quadrant selection in `abel.tools.get_image_quadrants()` if certain quadrants are excluded and symmetry is selected. I will work on (later).

So, I think that we are save to merge.

**Comment by rth** [comment]
@stggh Nice work for identifying the problem with the sample size!

@DanHickstein  Congratulations on your new job! Myself I'm also in a bit of a job transition at the moment (leaving the academia), so I will probably not be able to contribute to PyAbel much in the  future beyond some light maintenance. Still, I completely agree that we should  make the final push to get to v1.0 for PyAbel, and there are a number of points I should finish myself  :)
> we should make a final push to get the code documented, cleaned up, and ready for public consumption.  [...] we should get the documentation in working order and make the package look professional. Basically, the 1.0 release. 

@DanHickstein @stggh @DhrubajyotiDas I was thinking that it might be useful to make a short meeting to go through the open issue together, decide what needs to be done for v1.0 and what each us is willing to work on given his availability. As email (or github messaging) conversation tend to linger, it would it probably be more efficient to just make decisions in a viso-conference (I was thinking Google Hangouts).  

Because of the time difference this could be [a bit tricky](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20160210&p1=195&p2=57&p3=179&p4=75), but essentially something like,
   -  9 AM Canberra time (day before), 3PM Denver CO time, 5PM Eastern Standard Time (EST) and 11PM Paris time should work for all of us, I think.

*Note:* @DanHickstein I can't find the message where you mention the location of your new post-doc, I think it was not far from Texas, right? so in EST time, isn't it? @DhrubajyotiDas I'm not certain if you are in the EST time zone? @stggh Note, that there is a 1day difference in the date for Australia. 

Here is a poll to decide on the date: http://doodle.com/poll/xahg84847swz252x
Even if 3 out 4 of us can make it, that would already be great.  I will send the Google Hangouts link shortly before (it requires to have a gmail account).   What do you think?

**Comment by stggh** [comment]
Added in `abel/examples` a primitive GUI interface: `example_simple_GUI.py`
gui

Note, the code was concocted from various scrapings of the web. As you may tell I am unfamiliar with GUI programming, so this was a learning exercise.  I did attempt the Python Class approach, but it became too much of a mess.

**Comment by stggh** [comment]
Updated to include anisotropy calculation button:
gui

@DanHickstein, @rth, @DhrubajyotiDas   FYI

**Comment by rth** [comment]
@stggh Nice work for the GUI! For more sophisticated GUI application, PyQt is probably a more classical choice, but that would add another dependency (PyQt, Qt) while tkinter is builtin and does the job.

**Comment by stggh** [comment]
Agreed. I selected `tkinter` on the basis that is it builtin. 

Updated to include other methods:
gui2

**Comment by stggh** [comment]
This example has revealed some issues:
 1) Non-standard interfaces (known):
       `BASEX()` not defined as `iabel_basex_transform()`, and requires 3 parameters

   `onion_peeling()`  processes left side of image, size must be even (cf odd for all other, current, methods)

 2) `direct()` has an odd looking speed and anisotropy intensity variation (could be @stggh coding)

 3) `hansenlaw()` speed distribution not as sharp as `basex` or `direct` (@stggh finds this annoying :-( )

**Comment by DanHickstein** [comment]
@stggh, great work on fixing the inconsistencies with the quadrants and for making this cool new GUI! I had been pondering the idea of making a GUI for PyAbel for a while, and am happy that you have done so. 

In the interest of not having too many PRs open at once, should we merge this one and save future improvements to the GUI example for a future PR?

**Pull request merged**
