### PR TITLE
Spherical polynomials and improved SampleImage

### PR DESCRIPTION
**Pull request by MikhailRyazanov**
Here is an addition to `abel.tools.polynomial`, now implementing the analytical Abel transform of polynomials in spherical coordinates (bivariate polynomials in *r* and cos *θ*). A special case of them was already used for rBasex basis functions, but here they are generalized to arbitrary *r* powers and arbitrary radial limits.

This can be useful if somebody wants to model smooth VMI-like distributions, for example, by approximating them with cubic splines. But the main goal, also implemented here, was to provide high-accuracy Abel transforms of our sample images (`abel.tools.analytical.SampleImage`). The existing images are composed of Gaussian peaks, which don't have analytical Abel transforms, but they can be approximated by piecewise polynomials with any desired accuracy, and thus an arbitrarily accurate Abel transform can be obtained.

I've also added, for completeness, an isotropic Gaussian “blob” image (2D analog of `abel.tools.analytical.GaussianAnalytical`), which does have an analytical Abel transform. And an image resembling the “classic” calibration image for photofragment VMI (O<sup>+</sup> from O<sub>2</sub> 4-photon photodissociation/ionization), familiar from the Eppink–Parker work. It is composed of polynomials peaks, with maybe less experimentally looking shapes, but having an exact Abel transform.

Partial backward-incompatible changes to `SampleImage` (discussed in #337):
* `.image` attribute is deprecated in favor of `.func` (still works but prints a warning).
* `sigma` parameter is changed to absolute value in pixels instead of something strange. Default values reproduce the old behavior.
* Radial scaling is corrected: `.r_max` is now in pixels according to `n`, and all peaks radii scale proportionally to it (previously it was also doing something strange; see 8fb9b96e for old–new comparison, 39e39636 for the change). `'dribinski'` at its default `n=361` is not affected, `'Ominus'` at its intended `n=501` is also not affected but is slightly changed at other `n` values (I had to adjust the PES unit test slightly to account for this).

### CODE REVIEW

**Comment by MikhailRyazanov** [comment]
Travis complains about some deprecations in SciPy — I'll try to check whether they can be updated without breaking older versions... And it's probably time to update our outdated requirements in `setup.py`:
https://github.com/PyAbel/PyAbel/blob/e7e6b57ea1c6d679d67b3d0da4b5af45488c6910/setup.py#L104-L107

**Comment by MikhailRyazanov** [comment]
OK, I've updated the requirements to more reasonable versions — the last versions that support Python 2 or the oldest versions used in our tests (they all are at least 2 years old, so this shouldn't be a problem for anybody).

SciPy indeed had `scipy.ndimage.interpolation....` functions moved to just `scipy.ndimage....` a long time ago, so I've updated them everywhere (this also made that code slightly more compact).

(The PEP 8 warnings above are more or less irrelevant, so I'm going to ignore them unless somebody thinks different.)

**Comment by MikhailRyazanov** [comment]
I've added a forgotten test for even-sized sample images and also included a helper function to convert SciPy splines to polynomial parameters (“if somebody wants to model smooth distributions”).

**Comment by stggh** [comment]
(1) Pytest

Since you mentioned  `pyest`  I also checked. On my system (2013 Macbook + Ubuntu 21.10 - used while away from home) fails:
```
[MBP:.+-MR-spolynomial]$ pytest-3
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /home/stg121/Software/Python/PyAbel/PyAbel-MR-spolynomial
collected 114 items                                                            

abel/tests/test_basex.py ............F                                   [ 11%]
abel/tests/test_benchmarks.py ..                                         [ 13%]
abel/tests/test_dasch_methods.py .....                                   [ 17%]
abel/tests/test_daun.py .......                                          [ 23%]
abel/tests/test_direct.py ...ss                                          [ 28%]
abel/tests/test_hansenlaw.py .......                                     [ 34%]
abel/tests/test_linbasex.py ..                                           [ 35%]
abel/tests/test_math.py .                                                [ 36%]
abel/tests/test_onion_bordas.py ......                                   [ 42%]
abel/tests/test_rbasex.py ...............                                [ 55%]
abel/tests/test_tools_analytical.py ....                                 [ 58%]
abel/tests/test_tools_center.py ......                                   [ 64%]
abel/tests/test_tools_circularize.py .                                   [ 64%]
abel/tests/test_tools_distributions.py ................                  [ 78%]
abel/tests/test_tools_polynomial.py ................                     [ 92%]
abel/tests/test_tools_symmetry.py .                                      [ 93%]
abel/tests/test_tools_vmi.py ......                                      [ 99%]
abel/tests/test_transform.py .              

=================================== FAILURES ===================================
________________________ test_basex_forward_gaussian_07 ________________________

    def test_basex_forward_gaussian_07():
        """Check a gaussian solution for BASEX forward transform:
           small sigma, regularized"""
>       basex_forward_gaussian(sigma=0.7, reg=1e-6, atol=1e-3, rtol=1e-2)

abel/tests/test_basex.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

sigma = 0.7, reg = 1e-06, atol = 0.001, rtol = 0.01

    def basex_forward_gaussian(sigma, reg, atol, rtol):
        """Check a gaussian solution for BASEX"""
        n = 100
        r_max = n - 1
    
        ref = GaussianAnalytical(n, r_max, symmetric=False, sigma=30)
        tr = np.tile(ref.func[None, :], (n, 1))  # make a 2D array from 1D
    
        Ai = abel.basex.get_bs_cached(n, sigma=sigma, reg=reg,
                                      basis_dir=None, verbose=False,
                                      direction='forward')
    
        proj = abel.basex.basex_core_transform(tr, Ai)
        proj = proj[n // 2 + n % 2]
    
        ref = ref.abel
    
>       assert_allclose(proj, ref, atol=atol, rtol=rtol)
E       AssertionError: 
E       Not equal to tolerance rtol=0.01, atol=0.001
E       
E       Mismatched elements: 1 / 100 (1%)
E       Max absolute difference: 0.2182584
E       Max relative difference: 0.55454652
E        x: array([5.330450e+01, 5.304528e+01, 5.297141e+01, 5.252474e+01,
E              5.237165e+01, 5.169492e+01, 5.125186e+01, 5.039819e+01,
E              4.944562e+01, 4.864272e+01, 4.737616e+01, 4.667229e+01,...
E        y: array([5.317362e+01, 5.311457e+01, 5.293781e+01, 5.264453e+01,
E              5.223666e+01, 5.171690e+01, 5.108865e+01, 5.035601e+01,
E              4.952369e+01, 4.859703e+01, 4.758184e+01, 4.648445e+01,...

abel/tests/test_basex.py:190: AssertionError
=========================== short test summary info ============================
FAILED abel/tests/test_basex.py::test_basex_forward_gaussian_07 - AssertionEr...
================== 1 failed, 111 passed, 2 skipped in 28.12s ===================
```

(2) docs

Thanks for fixing `livehtml`. Make file requires the removal of `../` in the `livehtml:` command

```
[MBP:.+spolynomial/doc]$ diff Makefile oldMakefile 
0a1
> 
57c58
< 	sphinx-autobuild -b html --open-browser $(LIVEHTMLOPTS) $(BUILDDIR)/html
---
> 	sphinx-autobuild -b html ../ --open-browser $(LIVEHTMLOPTS) $(BUILDDIR)/html
```

**Comment by MikhailRyazanov** [comment]
This basex error looks very strange. I haven't changed anything related to basex itself, nor any *code* related to `GaussianAnalytical`. Neither can I reproduce it locally, even when reducing tolerances to `atol=0.96e-3, rtol=0.96e-2`, so it's not some edge case.
However, if I print `func` (the `x` array in the error message), I get
```
[5.33032149e+01 5.30440011e+01 5.29701365e+01 5.25234719e+01
 5.23703836e+01 5.16936728e+01 5.12506208e+01 5.03969673e+01
 4.94444211e+01 4.86415327e+01 4.73749931e+01 4.66711479e+01
```
which is *slightly* different from your printout (whereas `ref` — the `y` array — looks the same as yours).

Are your results reproducible? Could you check whether this test passes for the master branch?

**Comment by stggh** [comment]
Reproducible, and the same failure with master. 

I will follow up once I return to my home, on Sunday.

This PR is good to merge.

**Comment by MikhailRyazanov** [comment]
@stggh, do you have any updates on that problem?

**Comment by stggh** [comment]
Sorry, for the delay. Life in retirement is busy.

The `tests/test_basex.py` only fails on my Macbook Pro (retina 13" late 2013), running Ubuntu 21.10, for both Ubuntu and Anaconda python 3.9.7. It passes on the same laptop under OSX (Anaconda python 3.9.7).

I will investigate further, later.

**Comment by MikhailRyazanov** [comment]
OK, interesting. :–) I'll then merge this PR, but please report when you find out — as a new issue/PR if it's important and can be corrected, or just comment here if it was some local glitch...

**Pull request merged**
