### PR TITLE
Improve comments and tweak calc_speeds

### PR DESCRIPTION
**Pull request by DanHickstein**
In anticipation of the 0.6 release, I went through the basex.py, tools.py, and the examples and improved the comments the best that I could and removed old junk that no longer made sense. The only real tangible change that I made to the actual code was to change the behavior of calc_speeds to take only one input argument (just ``im`` and not ``n``). I think that this makes the most sense.

### CODE REVIEW

**Comment by rth** [comment]
Everything looks good. I think we can merge this. Unless @DhrubajyotiDas or @stggh have additional comments regarding issue #40 .

**Comment by DhrubajyotiDas** [comment]
This looks great! 

I don't have any issues with this PR and #40. I'm most likely going to re-fork PyAbel and rebase my changes regarding #27 once 0.6 gets released.

**Comment by rth** [comment]
@DhrubajyotiDas I think just a [rebase](https://github.com/rth/PyAbel/blob/contribution_guidelines/CONTRIBUTING.md#before-merging) (without reforking) should work for your fork after the 0.6 release, shouldn't it?

**Comment by DhrubajyotiDas** [comment]
It should, but it seems like I've made a few changes in my fork which won't transfer over cleanly after rebasing the 0.6 release. My local copy is backed up so I won't be losing any work, and starting over would mean working from a clean slate, especially given the naming conventions and other standards we've agreed to.

**Comment by DanHickstein** [comment]
Okay, I'd say that we go ahead and merge and move forward with the release so that @stggh and @DhrubajyotiDas can move forward with their new transforms. I leave it to @rth to hit the button :)

**Comment by rth** [comment]
@DhrubajyotiDas Well it's up to you depending on what you find better. FYI, I just tried to clone your fork and do a rebase on the current PyAbel master, and there is just one conflict that has to be manually fixed in the `basex.py` during this operation, but for the rest I think it works fine. The result for the `basex.py` is  in this [gist](https://gist.github.com/rth/833efa4f11c12110d4c6). An this way you keep your commit history...

**Comment by DhrubajyotiDas** [comment]
So I managed to rebase and took care of the conflicts (after a few botches), but I think my commit history got messed up in the process...

**Comment by rth** [comment]
@DhrubajyotiDas Wow, yes, it looks like now your git history counts every for your commit twice, and there is some merges going on Also the diff removes and add stuff from basex.. Sorry to have led you this way. Not sure what went wrong. When I did the rebase of your branch, I didn't have those problems. The state of your fork after I performed the rebase can be found at http://r0h.eu/d/PyAbel_DhrubajyotiDas_save_rebase.tar.gz (it a zip of the folder containing the clone of your fork after the rebase). Just to check I made another fork at https://github.com/luli/PyAbel and pushed this clone there, which made your commits appear cleanly in [the git history](https://github.com/PyAbel/PyAbel/network). 
So I think if you,
 1. Remove your fork from github (your commits are also saved at the https://github.com/luli/PyAbel fork now)
 2. Re'fork
 3. Unzip that file containing your clone
 4. Do a pull , then push to your fork, your git history should be cleaned up and contain all your commits. 

Let me know if that works... Sorry for the mess, git doesn't feel very straightforward at times...

**Comment by DanHickstein** [comment]
I am glad that I am not the only one baffled by the crazy creature called Git! :)

**Comment by DhrubajyotiDas** [comment]
@DanHickstein good thing we've got @rth to bail us out when we mess up!

@rth, my repo is back to healthy status again. Thank you so much for your help!

**Comment by rth** [comment]
@DhrubajyotiDas  Great! No problem.

**Comment by DhrubajyotiDas** [comment]
@rth Now that PR #43 has been pushed to PyAbel, when I try to rebase to put my changes on top (as per [your instructions](https://github.com/rth/PyAbel/blob/contribution_guidelines/CONTRIBUTING.md#before-merging)), I'm still getting duplicate commits.

(Screenshot of my git application, Sourcetree)

image

I haven't pushed the changes yet, so I can delete my local copy and clone my fork to undo this, but I'm afraid this situation is going to happen whenever I do finish my changes and file for the pull request. What is the safe/appropriate way to rebase #43 ?

**Comment by rth** [comment]
@DhrubajyotiDas Hmm, I see the problem. So are you doing the rebase with the Sourcetree application? I think that must be the issue, it must be doing something else in addition. I can look into it tomorrow. 

Yeah, don't push this update to the repo. I think, you can just re-clone, and merge the changes from master to your fork. I mean essentially both re-base and merge can be used to achieve the same thing, as far as I understand, and there is different visions as to [when to use each one](https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase/).  I think just using merge for now should be fine, until we understand why rebase produces that result on your computer.

**Comment by DhrubajyotiDas** [comment]
@rth I thought it was the Sourcetree application too, but executing the rebase git commands from terminal produce the exact same result. I think the duplicates might have something to do with the fact that the commits at the bottom of the screenshot have me as the author and you as the committer, while the ones at the top have me as both author and committer. That might make it appear as two different commits to git, and hence they get stacked. I'm not very confident of this hypothesis, but it might be possible. 

In any case, merge seems to have worked fine. This is the current state of my local repo; I'll wait for you to respond before pushing this to my fork.

image

**Comment by rth** [comment]
@DhrubajyotiDas Aww, yes, those commits appear to have you as the author and me as the commiter probably because I did the rebase of your repo that you then pushed (I didn't know this would happen). They still should count correctly in the list of contributors, and the merge you did looks good, so I think you can push this.

Yes, you are right, this mixed author/contributor thing could be an issue for the rebase, as I think one should rebase only one's own commits.  So maybe, in the future, after you do a PR to merge these changes into PyAbel, we can try to see if the rebase works with your future commits without this complication. For now I think just merging should work well.

**Pull request merged**
