### PR TITLE
Improvements to the readme

### PR DESCRIPTION
**Pull request by DanHickstein**
I changed the format of the readme to allow it to be incorporated into the documentation and appear on readthedocs.org. I also re-wrote a lot of it, so have a look and see what you think.

I also changed a line in the `conf.py` to use `sphinx.ext.napoleon` rather than `numpydoc`. I don't know when this got changed, but readthedocs.org uses Napoleon rather than numpydoc. Napoleaon can parse numpy-style docstrings as well as google-style ones, so there is no real reason to use numpydoc. 

I probably need to figure out how to rebase this PR, since I made tons of commits trying to figure out how the `.rst` files were going to render on GitHub and rtfd.org.

I'm leaving for a 3-day trip this afternoon, so it might be a few days before I get back to this.

@PyAbel/developers

### CODE REVIEW

**Comment by DanHickstein** [comment]
Oh, I think that I've successfully rebased everything down to one commit. This is the first time that I've been so successful in doing this! (The secret is to change git's default text editor to something that I know how to use (textmate) rather than silly vi, which I have no idea how to use.)

**Comment by DanHickstein** [comment]
I'm leaving town for a few days, I leave it to @stggh and @DhrubajyotiDas to proofread this and merge. If there are issues, I'd recommend to just merge this and then make a separate PR fixing the issues.

**Comment by stggh** [comment]
> I've successfully rebased everything down to one commit.

My own revelation was that the merge conflicts *could* be edited in vim, rather than some silly multi-panel GUI, that the issues are marked with `<<<` and one has a 50% chance of getting the edit right.

Have a good trip @DanHickstein, @DhrubajyotiDas will see how much damage we can do ;-)

**Comment by DhrubajyotiDas** [comment]
I resorted to using [DiffMerge](https://sourcegear.com/diffmerge/), which provides a really useful three-column layout when it comes to resolving merge conflicts.

**Comment by DanHickstein** [comment]
That diffmerge thing looks cool!

**Comment by DhrubajyotiDas** [comment]
@DanHickstein More info dump about 3-way-merging tools from [stackoverflow](http://stackoverflow.com/questions/572237/whats-the-best-three-way-merge-tool)

**Comment by stggh** [comment]
@DhrubajyotiDas I don't have many issues with @DanHickstein's great doc work. The matplotlib image should be included with the example program code. The file `CONTRIBUTING.md` has the "old" `f/iabel` function statement, which suggests a rebase may be required before the merge. The links point to the wikis, which I thought we were favouring removing the wiki (although, offhand I cannot recall where)? I see no issue in waiting the day or so for Dan to come back on line, because any changes will be via a new PR in any case. Sorry, not quite as efficient as you are @DanHickstein.

**Comment by DanHickstein** [comment]
@stggh, I can make these changes. For now, I intended to do away with maintaining the Wiki's "home" page, and instead link to the readme. The other wiki pages that describe the transforms should stay for now. It's probably a good idea to migrate them to `.rst` files and incorporate them into the documentation, but I think that we should leave this for a future project. 

I incorporated the new changes (although this somehow undid my clever rebasing and revealed the numerous silly commits, but this is not really a problem).

I will see about including the image in the readme.

**Comment by DanHickstein** [comment]
Hmmm, I am having some problems getting the changes that @stggh made to merge into this PR. I'm just going to close this one, delete the branch, and make a new one.

**Pull request closed without merging**
