### PR TITLE
Dasch cached memory basis

### PR DESCRIPTION
**Pull request by stggh**
This PR adds memory caching to the `dasch` methods (`onion_peeling`, `two_point`, `three_point`) and `linbasex`, in a similar manner to @MikhailRyazanov's `basex` work.  **Importantly**, `abel.tools.basis.get_bs_cached()` has been dropped, with `abel/tools/basis.py` removed, returning `get_bs_cached()` to each PyAbel method file `dasch.py` and `linbasex.py`. See #231. The differences in defining the basis files in a unique way meant that a common `get_bs_cached()` was useless.

The function `abel.{dasch/linbasex}.basis_cleanup()` from @MikhailRyazanov `basex` work has been added to delete the global basis variables.

`**kwargs` was dropped from `linbasex`, which exposed two old parameter name faults in the unit test and `linbasex` examples.

Testing. Perhaps, these could be unit tests, I am just worried about the execution time.
[code gist](https://gist.github.com/stggh/2e5ef31a8a211328d0091ea87a47e46c)
```
Dribinski image quadrant (251, 251) ========================================

(0) Generate basis ------------------------------

A suitable basis for 'three_point' was not found. A new basis will be generated.

three_point basis saved for later use to './three_point_basis_251.npy
                                                             ... in 12.8 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 0.7 ms

(2) Read basis from file ------------------------------

Loading three_point basis ./three_point_basis_251.npy
                                                             ... in 1.4 ms



Dribinski image quadrant (2501, 2501) ========================================

(0) Generate basis ------------------------------

A suitable basis for 'three_point' was not found. A new basis will be generated.

three_point basis saved for later use to './three_point_basis_2501.npy
                                                             ... in 1363.3 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 321.9 ms

(2) Read basis from file ------------------------------

Loading three_point basis ./three_point_basis_2501.npy
                                                             ... in 374.0 ms


 [remove small size basis file three_point_basis_251.npy]

Back to (251, 251) image size ----------------------------------------

(3) Cached from larger basis cache ------------------------------

Loading three_point basis ./three_point_basis_2501.npy
                                                             ... in 23.7 ms

(4) Read from larger basis file ------------------------------

Loading three_point basis ./three_point_basis_2501.npy
                                                             ... in 20.8 ms


 [clean up, remove basis files three_point_basis_2501.npy]

```
```
Dribinski image quadrant (51, 51) ========================================

(0) Generate basis ------------------------------

A suitable basis for linbasex was not found.
A new basis will be generated.
linbasex basis saved for later use to ./linbasex_basis_101_02_050_1_0.npy
                                                             ... in 11.8 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 6.1 ms

(2) Read basis from file ------------------------------

loading ./linbasex_basis_101_02_050_1_0.npy ...
                                                             ... in 6.5 ms



Dribinski image quadrant (251, 251) ========================================

(0) Generate basis ------------------------------

A suitable basis for linbasex was not found.
A new basis will be generated.
linbasex basis saved for later use to ./linbasex_basis_501_02_050_1_0.npy
                                                             ... in 143.7 ms

(1) Cached basis ------------------------------

Using memory cached basis
                                                             ... in 128.9 ms

(2) Read basis from file ------------------------------

loading ./linbasex_basis_501_02_050_1_0.npy ...
                                                             ... in 133.7 ms
```

Happy to make any changes.

### CODE REVIEW

**Comment by DanHickstein** [comment]
> Importantly, abel.tools.basis.get_bs_cached() has been dropped, with abel/tools/basis.py removed, returning get_bs_cached() to each PyAbel method file dasch.py and linbasex.py. See #231. The differences in defining the basis files in a unique way meant that a common get_bs_cached() was useless.

I think that this is the right move. It was a fine idea to try to unify the code, but I think that it turned out to be more complicated that way.

The code looks good to me!

**Comment by stggh** [comment]
rebased with PR #228 (I hope)

**Comment by DanHickstein** [comment]
I think that we can go ahead and merge this, right?

**Comment by stggh** [comment]
**Summary**
1) Dasch methods (`onion_peeling`, `three_point`, `two_point`)  caching of  the "basis" (deconvolution array)

    Mirrors the work of @MikhailRyazanov for the `basex` method. A previously calculated deconvolution array is saved, and used for any subsequent `dasch` method calculation, if the image size has the same or smaller width (number of columns). Otherwise, as usual, the basis file is read, if available. A larger basis array is sliced for use with smaller images.

    Note, unlike `basex` caching does not result in a massive time saving, since reading the small basis from a `.npy` file is also pretty efficient.  Reading and slicing from a much larger basis file may actually be slower than a small column size calculation.

2) Basis calculation function `get_bs_cached()` returned to `dasch,py`

    Due to substantial differences between `dasch`, `basex`, and `linbasex` basis file labelling,  a common `abel/tools/basis/get_bs_cached()` did not work. This basis generation function has been returned to each respective method file.  For `basex` it never left. `abel/tools/basis.py` has been removed.

3) `linbasex` caching, intensity, alignment

   Now also has a cached basis and local `get_bs_cached()` function.

   A factor of `1/2r` has been included so that the transform intensity matches the other `PyAbel` transforms, for real photoelectron spectra. `linbasex` transforms only 2D-square arrays, and so could not be calibrated using the 1D transform pairs.

   There are some issues with subpixel alignment that are being addressed, see #224, and it seem possible that `linbasex` should be able to transform 1/2-images, as has been achieved for `basex` #230 (?), making it consistent with the other `PyAbel` methods, and saving substantial transform time.

**Comment by MikhailRyazanov** [comment]
[`cache_cleanup()`](https://github.com/PyAbel/PyAbel/blob/f49e2212e3ced614dbe84a66c542f0aebf2ecf59/abel/dasch.py#L389-L393) should include `_source` in `global`. Or omit `_source = None`, if cleaning it is not needed.

**Comment by stggh** [comment]
Good point. Please add `_source` to the `global` list for your upcoming `basex` PR

**Comment by MikhailRyazanov** [comment]
OK!

**Comment by stggh** [comment]
> it seem possible that `linbasex` should be able to transform 1/2-images

I was a too optimistic with this statement. It can be done, but there is little to gain, as the size of the basis calculation is unchanged, and the part input-image sizes must be padded to perform the projection.

The issue is that the `linbasex` method sums along each row, to form a projection <math>L<sub>iu</sub> (right side intensity profile of this figure):
image
This profile is least-squares fitted to the sum of Legendre polynomial products, providing coefficients <math>p<sub>lk</sub></math>
image

Hence, the size of the basis array is proportional to the number of rows, which is unchanged for a `1/2`-image size. The calculation of the projection sum for each projection angle using `scipy.ndimage.interpolation.rotate()` also requires padding, for part images, in order to centre the image for the rotation. 

Code for the above in my [linbasex-half-image](https://github.com/stggh/PyAbel/tree/linbasex-half-image) fork.

So, nothing to gain from the original approach of duplicating the part image to form a full image for `linbasex` processing.  Although, I see `linbasex_transform()` assumes a quadrant image, so a little tidying of the original code is required. I will do this when I update the docs.

**Pull request merged**
